### ISSUE TITLE
Make code changes in snippets very visible

### ISSUE THREAD

**Issue by kgish** [balinterdi/rarwe-issues#100]
This is just a suggestion.

In the section ‘`Creating our application`‘ make the changed lines in ‘`bower.json`‘ explicit by marking them with some indicator so that the differences are immediately apparent to the reader.

This best practice can be used consistently throughout the book.

Another manner to achieve the same thing would be to provide github links to the changesets so the reader can see for himself.

For example, once at the end of each chapter.

**Comment by balinterdi** [comment]
That's actually an excellent suggestion, I'll come around to it in the near future.

**Comment by kgish** [comment]
Glad you agree.

Sure it might be a bit extra work for you, but in the end it would improve the readability greatly and make a fantastic book even better!

Here's an example screenshot from '`Agile Web Development with Rails`' which shows such a format that I found useful:
![image](https://cloud.githubusercontent.com/assets/79195/10304510/fbe99562-6c1a-11e5-8f32-eee166136a28.png)

Notice the small arrow indicator on the left-hand side showing the line which was added.

Hope this helps.

**Comment by balinterdi** [comment]
I imagine a method where modifications, additions and removals are all clearly discernible across all epub formats/devices. Prefixing lines with + and - might work and then modifications would have both, just as git does it.

**Comment by kgish** [comment]
OK! Just top let you know, I'm reading your book now for the second time.

**Comment by balinterdi** [comment]
Is it that good or that hard to understand? ;)

**Comment by kgish** [comment]
Not hard to understand, but dense enough for me to need to reread it all as a nice and relaxing refresher.

**Comment by balinterdi** [comment]
Makes sense, thank you, Kiffin.

**Comment by balinterdi** [comment]
Happy to report this is going out in the next book update, coming real soon:

![code-diff-example](https://cloud.githubusercontent.com/assets/5022/14016107/3b814a70-f1be-11e5-87b9-3c6b44f40bcf.png)

**Comment by kgish** [comment]
Excellent! Honored that you took my suggestion to heart and produced something so nice-looking.

**Comment by balinterdi** [comment]
You triggered my first time ever usage of an emoji on Github :)
