### ISSUE TITLE
Possible bug in filtering songs section

### ISSUE THREAD

**Issue by jluckyiv** [balinterdi/rarwe-issues#103]
This maybe user/reader error, or it might be an issue.

On page 207 of PDF, line 19 of the `bands-test` code sample, `visit('bands/1/songs');` causes me to get the following error: `Pretender intercepted GET /bands/1 but no handler was defined for this type of request`. Looking at `tests/helpers/http-stubs.js`, it doesn't look like that route is defined.

Modifying line 19 to use the helper `selectBand('Them Crooked Vultures');` works just fine, presumably because the app is not hitting the server when it selects the link for 'Them Crooked Vultures'.

**Comment by balinterdi** [comment]
I rewrote lots of things in the Testing chapter since – as you pointed out – the testing code snippets were not updated to use JSON API (the code repository itself was). So that problem will go away. (I just went through the Testing chapter yesterday following the book, all tests were green)
