### ISSUE TITLE
Small grammatical errors Ch 15, Animations, Tuning

### ISSUE THREAD

**Issue by jluckyiv** [balinterdi/rarwe-issues#105]
In the first paragraph:

"Widgets that make it evident how they should be used <s>and</s> are a pleasure to interact with."

In the second paragraph:

"Animations, if applied judiciously, can play a significant role in <s>this</s> **the** latter. By making <s>a transition</s> **transitions** more nuanced, <s>it</s> **they** can signal to the user what has changed."

Third paragraph:

"That <s>has</s> changed when Edward Faulkner released liquid-fire[,] which has since become an Emberr add-on and the de facto standard animation tool for Ember."

However, I would suggest a small rewrite altogether:

"**Rich** client-side applications can mean different things for different people, but most would agree that rich user interactions are a common feature. However, *rich* should not mean *confusing*. Widgets should be a pleasure to use, and their use should be evident. Components should give clear feedback on how the the user has changed the application's state, or whether it has changed at all.

Animations, if applied judiciously, can play a significant role in feedback. Nuanced transitions signal to the user what has changed. Toward this end, we will add a couple of simple animated transitions in this chapter."

**Comment by balinterdi** [comment]
Thank you, that sounds a lot better.
