### ISSUE TITLE
Make ajax-loader.gif accessible for readers and mention where it needs to go

### ISSUE THREAD

**Issue by balinterdi** [balinterdi/rarwe-issues#107]

**Comment by Oladele** [comment]
To get the image itself, I used http://www.ajaxload.info/ which generates a loading spinner conveniently named ajax-loader.gif

Where to place the image (in my case, using ember-cli 1.13.8):

> To add images, fonts, or other assets, place them in the public/assets directory. For example, if you place logo.png in public/assets/images, you can reference it in templates with assets/images/logo.png or in stylesheets with url('/assets/images/logo.png').

...per [Ember CLI Docs](http://www.ember-cli.com/asset-compilation/)

In our case that means placing the ajax-loader.gif image in  `public/assets/images/ajax-loader.gif`


Finally, in styles/app.css, change `.spinner` style definitions
from
`background: url('/images/ajax-loader.gif') no-repeat; `
to
`background: url('/assets/images/ajax-loader.gif') no-repeat; `

**Comment by balinterdi** [comment]
Duplicate of #158 and fixed in the latest release.
