### ISSUE TITLE
Now that SortableMixin is gone, Backstage - Mixins lacks context

### ISSUE THREAD

**Issue by jluckyiv** [balinterdi/rarwe-issues#110]
Previously, Templates and data bindings used the Sortable Mixin, which gave context to the Backstage - Mixins sidebar. Now, the SortableMixin isn't used in the chapter, which gives the Backstage sidebar less context.

**Comment by balinterdi** [comment]
That's true and I pondered whether to remove the section altogether. I decided to keep it there for the time being because Mixins are important enough to talk about them, even without context. Nevertheless, I still have it on the back of my mind to find a more suitable place for them.

**Comment by jluckyiv** [comment]
I agree that the section should remain. Don't you sleep?

**Comment by balinterdi** [comment]
I'm somewhat grumpy when I don't so I do ;)

It's 7:55am here and I just sat down 5 minutes ago to go through my emails quickly before breakfast. But you should be in bed already, shouldn't you? :)

**Comment by jluckyiv** [comment]
Unfortunately, I don't sleep much. I monitored my sleep for a while and found out I average 5-6 hours per night. I stopped tracking after that.

**Comment by balinterdi** [comment]
I should try that once, too. What did you use to monitor your sleep?

**Comment by jluckyiv** [comment]
I use the Sleep Cycle app.

**Comment by jluckyiv** [comment]
Back on topic (sorry), what about extracting the relevant code from [ember-legacy-controllers/addon/utils/sortable-mixin.js](https://github.com/emberjs/ember-legacy-controllers/blob/59aeb196e44daa474e96bc11cd6318af1d2b6010/addon/utils/sortable-mixin.js) and using that as a mixin?

**Comment by balinterdi** [comment]
No need to be sorry, I enjoy digressions :)

I'm not so keen on the idea of using a legacy mixin (or any other legacy thing) to explain a concept. I'd rather keep it (the concept of mixins) at the back of my mind and use it when the opportunity presents itself. Or have an extra chapter "Things that I think are important but I couldn't force into the application" :) at the end. It's funny but I might actually do it. It might even be better than its current place since then it's explicit that it doesn't have anything to do with the current feature we're developing. What do you think?

**Comment by eduardodeoh** [comment]
Hey @balinterdi, in section "Routing" -> Show a list of songs, did you use

```
var SongCollection = Ember.ArrayProxy.extend(Ember.SortableMixin, {
  sortProperties: ['rating'],
  sortAscending: false,
  content: []
});
```

So it appears SortableMixin disappeared from Ember 2.0. How to resolve this problem? Sorry, i'm beginner with Ember.js and i'm reading your book, ok.

**Comment by balinterdi** [comment]
Hey Eduardo,

Starting from the first 2.0 release of the book, I no longer use the SortableMixin as it's no longer present in Ember 2.0 as you correctly point out.

The updated code snippet is this one:

```js
var SongCollection = Ember.Object.extend({
  content: [],
  sortProperties: ['rating:desc'],
  sortedContent: Ember.computed.sort('content', 'sortProperties'),
});
```

The recent editions, that you should have received notifications from Gumroad about, all contain the updated snippets.

**Comment by eduardodeoh** [comment]
Thank you @balinterdi, i will review notifications :+1:

**Comment by balinterdi** [comment]
I've moved the Mixins to the Appendix, thank you, @jluckyiv .

**Comment by Arkham** [comment]
On the same note, I've found this line that's not accurate anymore:

> When developing an Ember application, _we will not have to manually inject the sortable mixin_ or create a separate class for holding and displaying a sorted list of items. The framework provides ways to do that, as we will see.

**Comment by balinterdi** [comment]
Good point, but I've actually greatly simplifed the first chapters by not sorting the bands (and thus not using the mixin). Also, I've created an Appendix to contain some sections that don't fit well the flow of explanation in the chapter, and that's where I moved the Mixin section to. This will go out in the next update, coming out soon.

**Comment by Arkham** [comment]
Thanks, you're a :star:
