### ISSUE TITLE
Bringing over the definition of the Song class from the songs route. p.63

### ISSUE THREAD

**Issue by tenzan** [balinterdi/rarwe-issues#111]
At page 63, there's an expression:
>We simply brought over the definition of the Song class from the songs route.

Does it mean we move (not copy) the definition of the Song class? Or we keep it?

But from page 64:
> We again copied the songs from the songs route from the previous chapter and added a new one...

So I assume we here copy (not move) the content... Otherwise, it'd better to mention to remove from the Song class.

Thanks.

**Comment by balinterdi** [comment]
You're right, this can be misleading. I meant moving in both cases, I'll amend the text.

**Comment by tenzan** [comment]
Thanks, Balint.
