### ISSUE TITLE
app/templates/bands.hbs (p. 75)

### ISSUE THREAD

**Issue by tenzan** [balinterdi/rarwe-issues#112]
Hello!

I've read up to page 78 and I'm supposed to be able to navigate between the bands.

But it's showing up the blank page at `http://localhost:4200/bands`.

Ember console's showing the error:
> Uncaught TypeError: Object.defineProperty called on non-object

My related commit is https://github.com/tenzan/rarwe/commit/24840e7cb2372a937bf1edcc04d81aa5e4a3df42

I suspect this might be related to the code for `app/templates/bands.hbs` at page 75.

Thanks.

**Comment by balinterdi** [comment]
The definition of the slug property of the [band is incorrect](https://github.com/tenzan/rarwe/blob/24840e7cb2372a937bf1edcc04d81aa5e4a3df42/app/routes/bands.js#L7), you turn a method to a property using both the old method (calling `property` on the function) and using `Ember.computed`. You cannot use both at the same time.

I removed `.property('name')` from the end and now it works:

```js
var Band = Ember.Object.extend({
  name: '',
  language: '',

  slug: Ember.computed('name', function () {
    return this.get('name').dasherize();
  }),
});
```

Please also remove the definition of the `site` property, it was just meant as a digression in the Backstage section.

**Comment by tenzan** [comment]
Thanks, Balint,

So, we don't have to apply the code from _Backstage_ section, right?

**Comment by balinterdi** [comment]
No, but that was just the site property, which was unused. The problem was that the `slug` property was defined as follows:

```js
slug: Ember.computed('name', function () {
    return this.get('name').dasherize();
}).property('name')
```
