### ISSUE TITLE
Update Deployment chapter after Divshot acquisition by Firebase

### ISSUE THREAD

**Issue by asianfilm** [balinterdi/rarwe-issues#115]
Perhaps we need a Firebase Hosting or other deployment option since Divshot is being shuttered after the Firebase acquisition.

**Comment by balinterdi** [comment]
Good point. I'm not sure how much Divshot deployment and the ember-cli-divshot will need to change, it might be the case that the command should just be "ember firebase push development" instead of "ember divshot push development" :) . I'll track the changes/options.

**Comment by tompagabor** [comment]
Just install firebase-tools with npm then log into firebase width "firebase login", run "firebase init" and then you have to build your app and deploy it to firebase (ember build, firebase deploy). I didn't find automatic build in firebase command line tool.

**Comment by balinterdi** [comment]
I've replaced Divshot with [PageFront](https://www.pagefronthq.com/), and instructions will be included in the next release of the book.
