### ISSUE TITLE
Bootstrap glyph fonts not configured

### ISSUE THREAD

**Issue by jsmestad** [balinterdi/rarwe-issues#12]
On page 66 your using `<span class="pointer glyphicon glyphicon-chevron-right"></span>` which tries to load the `glyphicons-halflings-regular.{eof,ttf,woff,woff2,svg}` files from the bootstrap library. Those are not configured at this point. - How do we get them to load? The book does not seem to call it out how to do that step.

**Comment by balinterdi** [comment]
Thank you, I've fixed that. In the Templates and data bindings chapter we specify `bootstrap` as a dependency and import its css. However, we should also import the fonts (and the source map) which is missing from the current edition:

```js
// Brocfile.js
(...)
app.import('bower_components/bootstrap/dist/css/bootstrap.css');
app.import('bower_components/bootstrap/dist/css/bootstrap.css.map', { destDir: 'assets' });
app.import('bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.eot', { destDir: 'fonts' });
app.import('bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.svg', { destDir: 'fonts' });
app.import('bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf', { destDir: 'fonts' });
app.import('bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff', { destDir: 'fonts' });
app.import('bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2', { destDir: 'fonts' });

module.exports = app.toTree();
```

This will go out in the next release.

**Comment by jsmestad** [comment]
@balinterdi what is line about? It's also not mentioned anywhere:

```
app.import('bower_components/bootstrap/dist/css/bootstrap.css.map', { destDir: 'assets' });
```

**Comment by balinterdi** [comment]
It is the Bootstrap source map. It is mentioned (although not elaborated on) in the updated text of the chapter.
