### ISSUE TITLE
li elements no longer inside ul - pg 108

### ISSUE THREAD

**Issue by ricky1981** [balinterdi/rarwe-issues#120]
"First, let's display the blurb with the call to action when there are no songs (while also changing the ul tag with the songs class to a div):"

This is pretty poor practice, li elements should belong to an ol, ul or menu. At the very least there should be some acknowledgement of this, better yet, the songs should be moved into a proper list.

http://w3c.github.io/html-reference/li.html

**Comment by balinterdi** [comment]
To clarify, when I change to divs, everything is a div, including the list container, so at no point are there `li`s inside of `ul`s. I agree that it'd be better to have ul-li and I'm not 100% sure why I had changed it.
