### ISSUE TITLE
pg 131 - Unsure on jQuery reference

### ISSUE THREAD

**Issue by ricky1981** [balinterdi/rarwe-issues#122]
"(Ember.$() is an alias for jQuery's top-level variable)"

But Ember.$() doesn't appear on the page? $ is used in the ES6 template string so maybe add a reference back to pg 28?

**Comment by balinterdi** [comment]
Thank you, this had been fixed in #94 and should be included in the next release. (Before I used `Ember.$(document).attr('title', ...)` to set the title hence was the need for the explanation of Ember.$()).
