### ISSUE TITLE
pg 201 - minor typo "isComlpete"

### ISSUE THREAD

**Issue by ricky1981** [balinterdi/rarwe-issues#130]
"model.@each.isComlpete" - should be "model.@each.isCompleted"

**Comment by ricky1981** [comment]
I'm an idiot and didn't read the rest of the text although I think there is still a small typo in some of the text in that section as there is a mix of isComplete and isCompleted

**Comment by balinterdi** [comment]
Thank you, Ricky, that's a good point. I rewrote it to be consistently `isCompleted` (and mistyped to `isComlpeted` on one occasion).
