### ISSUE TITLE
Odd, asymmetric behaviour: Raised once, the create songs question is never again raised

### ISSUE THREAD

**Issue by fknoll** [balinterdi/rarwe-issues#138]
The controller 'app/controllers/bands/band/songs.js' is a singleton. Therefor the hash/property 'canCreateSong' is shared between all songs from all instances of bands. This gives and odd and asymmetric behaviour of the RARWE application. When 'canCreateSong' is once set to 'true' by clicking in the question/link "There are no songs yet. Why don't you create one?", then the question is never again raised for other existing or newly created bands without songs.

I therefore propose the hash/property 'canCreateSong' is reset to 'false', whenever a band is selected/clicked. I propose this to be accomplished in route "app/routes/bands/band.js" using:
afterModel:
function(band, transition) {
    this.controllerFor("bands.band.songs").set('songCreationStarted', false);
}

**Comment by balinterdi** [comment]
Good catch, that's a very subtle bug that [I wrote about a while ago](http://balinterdi.com/2014/06/26/ember-gotcha-controllers-are-singletons.html) but that seems to have made its way into the book, too.

An even more appropriate fix that I've learned about after writing that blog post is to use the [`resetController` hook of the route](http://emberjs.com/api/classes/Ember.Route.html#method_resetController):

```js
resetController(controller) {
  controller.set('songCreationStarted', false);
}
```

When routable components take over, no state will linger on them, so this issue will be moot, but I'll fix this before that.

**Comment by fknoll** [comment]
Yes, using the resetController hook on the songs route (app/routes/bands/band/songs.js) definitely works! It is a good solution. Thank you :-)

**Comment by balinterdi** [comment]
Thank you, let me just keep it open until I add an explanation in the code, too.
