### ISSUE TITLE
Replace ember-cli-bootstrap with ember-bootstrap

### ISSUE THREAD

**Issue by asianfilm** [balinterdi/rarwe-issues#139]
You can now just run `ember install ember-bootstrap` without needing to import the assets manually.

Even if you want to show readers how to introduce Bootstrap manually, I urge against it. It's a major road bump that slows down the learning. Perhaps add a sidebar explaining what it does, or even an Appendix showing how to make your own Bootstrap (or SemanticUI, etc) addon that does the same thing.

FYI, the command installed the 0.5.0 version of ember-bootstrap, released on 12 Nov 2015.

**Comment by balinterdi** [comment]
Thank you, that's actually already on my list and the next update should contain this.
