### ISSUE TITLE
Inconsistent use of single and double quotes

### ISSUE THREAD

**Issue by asianfilm** [balinterdi/rarwe-issues#140]
First, note that I'm reading the .epub version on my iPad in iBooks. In the .epub version, two single quotes looks like one double quote. For example, in the code block presented on page 27 of the 25 Nov PDF version, where `Song` extends `Ember.Object`, it really looks like the `title` and `band` properties are each set to a hanging double quote (`"`) rather than closed single quotes (`''`). A font issue I presume.

But that also points to inconsistent use of single and double quote throughout the code in the book. For example, on Page 29 of the 25 Nov PDF version, in the CLASS AND INSTANCE PROPERTIES backstage sidebar, you use both single and double quotes for the value of the `name` property on lines 2 and 16 respectively. In a section explaining the uniqueness of the back-tick, that is especially unnecessary.

I imagine many of your readers come from Ruby where single and double quotes have special meanings.

**Comment by balinterdi** [comment]
Good point, I went through the book and applied consistent quoting, single quotes in javascript code and double-quotes in templates and values that are outputted by the browser console (mostly in backstage sections in the book), which seems to be the common practice in Ember.
