### ISSUE TITLE
Switch to Ember CLI 2.2.0-beta.2 or later

### ISSUE THREAD

**Issue by asianfilm** [balinterdi/rarwe-issues#141]
Another stumbling block for me was the Setting up Ember CLI chapter. I put the book down at that point after the 25 November update, finding inconsistencies between the `bower.json` produced by your output from 1.13.12 and my output from 1.13.12. I went down a rabbit hole of researching what `resolutions` meant. This early in the book, manually messing with configuration files, is a major roadblock.

This time going through the book, I updated Ember CLI to 2.2.0-beta.2 and I didn't need to touch `bower.json`. I'm about a third of the way through the book now, and I've had no deprecations warnings, so I think it's all good to go. I did have to research how to properly uninstall my previous installation of Ember CLI, which should be detailed in the text. I had to run:

    npm uninstall -g ember-cli
    npm cache clean
    bower cache clean
    npm install -g ember-cli@2.2.0-beta.2

**Comment by balinterdi** [comment]
This is a valid point. Ideally, I'd have waited until Ember CLI drops the beta suffix but I think it's stable enough now that I can safely do the update. I've now done this, to 2.2.0-beta.3.
