### ISSUE TITLE
Confusing Component chapter

### ISSUE THREAD

**Issue by asianfilm** [balinterdi/rarwe-issues#142]
The Components chapter - in which a star-rating component is created - is the first that left me confused, and not because of the concepts but because of the presentation. I think it needs a restructuring.

The introduction is good, explaining the concept of components. My first point of confusion was the "headless" code extract that illustrates concatenated properties. There's no filename heading indicating where it goes and it doesn't work in the console. So I started looking at the code repository on Github to see where it's meant to be. Finally, I realise it's just for illustrative purposes.

The next section is headlined "Displaying the rating with stars", and that is exactly what I want right now, but it also adds hooks to set and update rating. I just want to see the code that displays the star rating first before adding any additional functionality. And the diversion into Ember pre-1.10 is a major distraction here; put that stuff in an Appendix focused on reading/updating legacy code.

Anyway, I'm writing the code as I go along and the stars aren't showing up. I don't know if I've mistyped something so I'm back to the Github repository, which just confuses me more. As in an earlier chapter, let me know not to expect any visible stars yet. Better yet, show all the code necessary to get the stars showing up (without updating them) and then break it down in the text. It's 25 lines of Javascript.

And how the Javascript works isn't clear. Add a paragraph stating that it builds an array of filled-in stars using the `starRange` helper function, then an array of hollowed-out stars (using the same helper), and then return the concatenation of the two arrays to the template, which iterates thorough them. Explain where `glyphicon-star` and `glyphicon-star-empty` come from; presumably Bootstrap.

(Throughout the book I've found your decision to exclude the `import Ember from 'ember';` at the top of code snippets confusing. It's not a lot of extra code to add to the book. Don't make me think about whether to include it or not, when my mind is focused on learning something new. The suggestion to use bold for new code would also hope in keeping one focused.)

There's lots of new ideas introduced in the chapter: component block-forms (and `yield`); normal vs concatenated properties; the necessity of dashes in component names; the two-way bindings created when one uses unquoted passed-in values; prefacing CSS properties with `:` when mixing static and dynamic CSS class assignments (in the legacy Ember section). But it's too condensed.

Until this point, the book has been crystal clear. It's the first chapter that I've reached that frustrated me for the Ember learning rather than for tooling shortcomings. Take that as a compliment.

**Comment by asianfilm** [comment]
I've now finished the chapter. If closure actions are always preferable, introduce them first before the (pre-Ember 1.13) passing of action name strings. Having learnt the legacy approach, I'm not ready to cleanly edit what I've just learnt with an alternative approach. The legacy/alternative approach can be in a sidebar or appendix. If you're concerned about the necessity of introducing a controller, then shift closures (and the updating/setting of the star rating) to the next chapter.

Also, explain why `on-click` needs to be quoted, presumably due to the hyphen/dash in the name.

**Comment by balinterdi** [comment]
Hey Stephen,

This is fantastic feedback and there are a ton of ideas that will make the book (even :) ) better. Here are the tasks that I'm going to extract from your above comments:

* Create an Appendix for more advanced concepts and move the section about concatenated properties there (I'll need a good music analogy for the title of the Appendix :) )
* Only display the stars first and only then add the necessary action (and markup) to set the rating
* Explain in detail the code needed to display the full and hollowed out stars
* Have `import Ember from 'ember'` everywhere it's needed (throughout the book)
* Explain why `this['on-click']` needs to be quoted
* Introduce closure actions first (this needs further consideration as the Actions chapter already introduced element actions before we got here)

I'd already removed the bind-attr Ember 1.10 legacy section which makes the number of new issues and distractions lower but I totally agree, there are ways to facilitate comprehension here and I'll do just that. 

Thank you very much for your insights.

**Comment by fknoll** [comment]
@balinterdi Music analogy for the title of the Appendix = **Encores**

**Comment by balinterdi** [comment]
Yes, I'd have liked that to be the title of a (semi-secret) sequel of the RARWE book, covering advanced topics so it's good to see it'd resonate with people :) I think it (the extra 4-5 songs a band plays when they are appauded back on stage) is actually in singular (Encore), but I'm not sure.

**Comment by zzr994** [comment]
>(Throughout the book I've found your decision to exclude the import Ember from 'ember'; at the top of >code snippets confusing. It's not a lot of extra code to add to the book. 

Ember-cli has made it easy to create new ember artifacts. if new artifacts are created using "ember generate ...." command, the ember import is automatically inserted into all the stubs. Only the rest of the code needs to be typed in. Hence missing import did not become an issue.

**Comment by balinterdi** [comment]
@asianfilm I made serious changes to the Components chapter based on your suggestions and indeed it is now much more easier to follow. You can see in the above list all the things I changed and I also moved all of the Backstage sections to an Appendix. Thank you once more for this!
