### ISSUE TITLE
Chapter 11 - Making the first test pass - Ed. Nov 23rd, 2015

### ISSUE THREAD

**Issue by tuvya** [balinterdi/rarwe-issues#143]
just a minor issue: 

on line 4 of the first acceptance test the path to "start-app" includes a wrong project name "new-project". should imho be "rarwe".

a very good read. extremly helpful. thank you so much.

**Comment by balinterdi** [comment]
Thank you, I've already fixed this on 12/02/2015 , so it will make it into the next release. And you're right, it should be `rarwe`.
