### ISSUE TITLE
Unable to run tests at all due to content security policy and/or live-reload issue(?)

### ISSUE THREAD

**Issue by tomwayson** [balinterdi/rarwe-issues#144]
Chapter 11. Trying to load http://localhost:4200/tests shows a page w/ an empty rectangle and the following error in the console:
```
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' localhost:49152 0.0.0.0:49152". Either the 'unsafe-inline' keyword, a hash ('sha256-37u63EBe1EibDZ3vZNr6mxLepqlY1CQw+4N89HrzP9s='), or a nonce ('nonce-...') is required to enable inline execution.
```
![image](https://cloud.githubusercontent.com/assets/662944/12080043/ea7bf2ce-b202-11e5-9129-d52241a60189.png)

I tried adding `'unsafe-inline' to the 'development' environment's 'script-src' content security policy as follows:

```js
  if (environment === 'development') {
    // ENV.APP.LOG_RESOLVER = true;
    // ENV.APP.LOG_ACTIVE_GENERATION = true;
    // ENV.APP.LOG_TRANSITIONS = true;
    // ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
    // ENV.APP.LOG_VIEW_LOOKUPS = true;
    ENV.contentSecurityPolicy = contentSecurityPolicy;
    ENV.contentSecurityPolicy['script-src'] = "'self' 'unsafe-eval' 'unsafe-inline'";
  }
```
After stopping the current development server and re-running `ember serve` I see that the console error goes away (the warning about require.unsee is still there) , but the page still just shows an empty rectangle.

Up until this point, everything has been working fine _except_ live-reload, which has not worked for any of the chapters, but has not kept any of the examples from working - I've just been reloading the page by hand. I wonder if that has something to do w/ it, b/c the last request in the network panel is a pending GET request for livereload.js:

![image](https://cloud.githubusercontent.com/assets/662944/12080085/e5db70b2-b204-11e5-90c8-85359edc8273.png)

You can see my configuration settings (environment.js, package.json, bower.json) at [this commit in my rarwe repo](https://github.com/tomwayson/rarwe/tree/e14582d9e3116a3f0129f2756161cf32b65e4c56).

I'm on Windows 7, and have gone through the [instructions here](http://ember-cli.com/user-guide/#windows) to improve performance and have been running my terminal window w/ elevated (Administrator) permissions as suggested.

**Comment by balinterdi** [comment]
Hey Tom,

I checked out your repository and all tests pass on my machine (OSX) except for the generated component integration test for the star-rating component. There is one thing I've found in your repo that might be the cause: the loader.js dependency in `bower.json` should be `3.4.0` (in the book, I first define this correctly but in a later snippet, I've accidentally written `3.2.1`.

I hope that helps because I don't know what else can go wrong. Live reload should just work and I've never seen it not work so far so I suspect it might be a Windows issue. Does it fail in other Ember projects, too?

The error about the inline script execution cannot be the cause of your woes because it is "Report only", it does not actually block the execution of the script.

**Comment by tomwayson** [comment]
Thanks Balint,

I was able to load my repo onto a Mac, and can confirm that livereload works and the tests run. I then updated to 3.4.0 version of the loader. That seemed to take care of the console warning, but I'm still not able to run tests on my windows machine. Tomorrow I will try running another ember app on my windows machine and see if livereload/tests work.

**Comment by tomwayson** [comment]
FYI - I tried running another Ember.js app on my Windows machine today and it appears that livereload is not working for me there either. I will continue with the book on my Mac. If I'm able to figure out the root cause of the issue on my WIndows PC I will report back here in case other users experience the same issue.

**Comment by balinterdi** [comment]
This might very well be an Ember CLI issue then. Ember CLI has come a long way with regards to Windows support but the experience is still inferior to having a "proper" POSIX shell. Consider reporting the issue there so that they have a chance of fixing it.

**Comment by fknoll** [comment]
I am working on a Windows 7 laptop, and I do not have access to an OSX machine.

I confirm to have been though exactly the same struggling with testing as Tom. I did not find a solution. Therefor I have decided to postpone working my way through all material in the Rock & Roll textbook related to test.

Balint, I guess serval of your current and future reader are using and will be using Windows OS. Until Ember CLI Test is confirmed to be correctly working on Windows OS, may be a warning in your textbook would be a highly appreciated by readers working on the Windows OS platform?

**Comment by balinterdi** [comment]
@fknoll You mean livereload does not work for you either AND the testing panel is blank, too? Good idea about adding a note for Windows users, I'll add that.

**Comment by fknoll** [comment]
@balinterdi Yes, my experience exactly matches the description by @tomwayson - a test page with an empty rectangle and no live reload.

I stumbled over this interesting Ember CLI issue: https://github.com/ember-cli/ember-cli/issues/5123.

Inspired by the discussion in this issue thread, I restarted my ember server with ```ember serve --host 0.0.0.0```. This “trick” fixed the problem with ```http://localhost:4200/tests``` displaying a page with an empty rectangle.

I am not sure about "Live reload". I changed some text in a ```<h3>``` tag in ```app/templates/application.hbs```, but I did not experience any automatic "refresh/reload" of the application.

**Comment by fknoll** [comment]
Restarting my ember server with ```ember serve -lrp 9000``` solves the "live reload" problem ... and ```http://localhost:4200/tests``` is still working.

**Comment by tomwayson** [comment]
thanks @fknoll!

I can confirm that `ember serve -lrp 9000` fixes live reload issue and enables running tests w/ `http://localhost:4200/tests` on my Windows PC.

@balinterdi you can close this issue now unless you want to keep it open while you're working on adding a note for windows users.

**Comment by balinterdi** [comment]
Thank you, Tom, I'd already added a note to Windows users.
