### ISSUE TITLE
Introduce controller-scoped query params to retain the value of the sorting direction between bands?

### ISSUE THREAD

**Issue by fknoll** [balinterdi/rarwe-issues#145]
**Textbook Reference:** Chapter 12, Sorting and searching with query parameters, page 227 (page 234 in PDF)

**Code Reference:** app/controllers/bands/band/songs.js

**Code Snippet:**

```
queryParams: {
sortBy: 'sort',
searchTerm: 's'
}
```

**Ember -v:**
version: 2.2.0-beta.2
node: 4.2.3
npm: 2.14.10
os: win32 x64

**Console:**
Ember: 2.2.0
Ember Data : 2.0.1
jQuery: 1.11.3

Despite the intentional additions to the URL, then the introduction of `queryParams` also seems to have an important impact on functionality: The songs controller is no longer totally a singleton with values for variables globally shared between different instances of songs routes.

Now, specific values for the controller variables `sortBy` and `searchTerm` set for a specific band survives between toggling bands - each band seems to have its own set of `queryParams`?

Is this behaviour desired/intentional?

**Comment by balinterdi** [comment]
Good insight, thank you.

> Despite the intentional additions to the URL, then the introduction of queryParams also seems to have an important impact on functionality: The songs controller is no longer totally a singleton with values for variables globally shared between different instances of songs routes.

> Now, specific values for the controller variables sortBy and searchTerm set for a specific band survives between toggling bands - each band seems to have its own set of queryParams

I'd say controllers are still singletons, it's just that Ember automatically resets the properties bound to query params (`sortBy` and `searchTerm`) when the model changes. There is [a very good section](https://guides.emberjs.com/v2.2.0/routing/query-params/#toc_sticky-query-param-values) on this in the Ember guides.

> Is this behaviour desired/intentional?

Let's just say that I like how it works out-of-the-box. I don't want the search term to persist between two different bands. Actually, it might make more sense for the sorting option (`sortBy`) to be retained between different bands. Here is how you'd do it:

```js
// app/controllers/bands/band/songs.js
import Ember from 'ember';
import { capitalize } from '../../../helpers/capitalize';
const { Controller, computed } = Ember;

export default Controller.extend({
  queryParams: {
    sortBy: {
      as: 'sort',
      scope: 'controller'
    },
    searchTerm: 's'
  },
  (...)
```

Let me give it some thought, I might include this in a future release.

Thank you!
