### ISSUE TITLE
Unable to persist songs to the server

### ISSUE THREAD

**Issue by camskene** [balinterdi/rarwe-issues#151]
Adding a song seemingly succeeds (the server responds with a 201 and the payload) however when the page is refreshed there are no songs.

**Comment by balinterdi** [comment]
Could you give more details? I've checked this and I see both bands and songs created by readers. 

There is a daily script that deletes all bands and songs and seeds the database with the original data set, so there is a very slight chance you created the song right before the daily run of the task.

**Comment by camskene** [comment]
When I load the page `/bands/1/songs` the songs model has a length of 0. I've been over it _many_ times and can't determine why I don't see any songs returned from the API. Perhaps you could enlighten me? My repo is here https://github.com/camskene/ember-rock-cli

**Comment by fknoll** [comment]
@camskene How do you check for the length of the **songs** model?

I would expect length of the **songs** model to be **1**; the current band:
```
// app/routes/bands/band/songs.js

import Ember from 'ember';

export default Ember.Route.extend({
	model: function() {
		return this.modelFor('bands.band');
	},
```
The length of the *song* model probably is **7**; equal to the number of songs for the current band -Pearl Jam, with id 1. This is also what the 'Ember Inspector' shows.

**Comment by camskene** [comment]
@fknoll to check the length of `songs` for band I do the following:

* Navigate to `http://localhost:4200/bands/1/songs` (Pearl Jam, no songs are displayed)
* In Ember Inspector click this `$E` to get the controller 
* In the console write `$E.get('model').get('songs').length`

I'm getting `0`.

![image](https://cloud.githubusercontent.com/assets/507499/12514134/bd497f78-c0ef-11e5-9f9f-c6887eb6b744.png)

**Comment by camskene** [comment]
I upgraded Ember and Ember Data to 2.3 and the songs now displa. Previously I was using v1.13. Thanks @balinterdi and @fknoll.

**Comment by balinterdi** [comment]
@camskene Cool this got resolved, thank you, @fknoll . Can I close this issue?

**Comment by camskene** [comment]
Resolved. Closing.
