### ISSUE TITLE
Bootstrap markup (and CSS) missing in latest book update

### ISSUE THREAD

**Issue by asianfilm** [balinterdi/rarwe-issues#153]
In the new revision of the book, which introduces the `ember-bootstrap` add-on, you removed a lot of complexity from the **Adding Assets to the Build** chapter, but also stripped out the parts where you introduced the markup (and CSS) necessary to prettify the page. 

Actually, maybe you should include all the CSS up-front (for the reader to type or copy-and-paste from Github) so that one is not going back and adding to it all the time. After all, styling isn't the focus of the book. Perhaps another framework, like SemanticUI, would need less prettifying.

**Comment by asianfilm** [comment]
PS: I'm going through the book once more and actually I'm okay with the way that the CSS is introduced at the start of each chapter. It's a good compromise in keeping it out of the way.

**Comment by balinterdi** [comment]
True, thank you. This was fixed by the same change that closed #159
