### ISSUE TITLE
Explaining "resolutions" in the initial bower.json

### ISSUE THREAD

**Issue by asianfilm** [balinterdi/rarwe-issues#154]
It's great that you're using the latest Ember-CLI beta in the new book update, such that my `bower.json` file matches your `bower.json` file. As a reader learning Ember, I want them to match.

But there's one difference. I have something called `resolutions` (in which `ember` is 2.2.0 and not 2.3.0). Presumably it's not just me seeing this in, which case it would be good to explain it.

```
{
  "name": "rarwe",
  "dependencies": {
    "ember": "2.3.0",
    "ember-cli-shims": "0.1.0",
    "ember-cli-test-loader": "0.2.2",
    "ember-load-initializers": "0.1.7",
    "ember-qunit-notifications": "0.1.0",
    "jquery": "1.11.3",
    "loader.js": "^3.5.0"
  },
  "resolutions": {
    "ember": "2.2.0"
  }
}
```

Perhaps I missed it in the revised text, but perhaps you can mention that `ember-data` used to be included as standard by Ember-CLI, but since 2.3.0 is now an Ember add-on.

Perhaps also explain why `ember-data` is still appearing in our `package.json` files...

**Comment by balinterdi** [comment]
Good point, thank you.

I'm not sure how you can have `2.2.0` as your resolution for `ember` when you have `2.3.0` defined as a dependency. Did you start to develop the app when it still ran on `2.2.0` and then changed the ember dep to `2.3.0`?

> Perhaps also explain why ember-data is still appearing in our package.json files...

Now it is only the only place it needs to appear, it no longer needs to be in `bower.json`, too. I tend to write less and less about how things were in the past. I might put these legacy concerns in an Appendix.

**Comment by zzr994** [comment]
We are still using Ember 1.x in our products.  So it is very useful for me to know the legacy stuff while reading this book. So please keep this information in the book. Thanks.

**Comment by balinterdi** [comment]
The downside of keeping all legacy stuff around is that it distracts the reader from focusing on what is there now. I can keep some of the "In earlier versions of Ember" sections in the book but at the same time I don't want to add to the cognitive burden of those who want to learn the latest stable Ember.

The good think about releasing new updates regularly is that you have all the previous book versions, too, so you can look up, say, how it was with Ember and ED 2.1.

**Comment by asianfilm** [comment]
I agree that previous versions of the book are the solution for people working with Ember 1.x. I'd even suggest bringing some of the "tricks" in the ES2015 chapter into the main text.

Regarding your question above, that's from an app freshly created with 2.3.0. Confuses me also. If nobody else is seeing it, then ignore it. Maybe it's a problem with my system.

**Comment by balinterdi** [comment]
> I agree that previous versions of the book are the solution for people working with Ember 1.x. I'd even suggest bringing some of the "tricks" in the ES2015 chapter into the main text.

You mean the advanced, ES2015 features? Like using `let` or destructuring from the start?

**Comment by asianfilm** [comment]
Yes, exactly.  Since Ember CLI is using a preprocessor, I'd treat them as "Ember native".

**Comment by zzr994** [comment]
As it is the learning curve for learning Ember is quite steep.  If you bring in ES2015 right in the beginning then it will make it even more harder.  I like the way ES2015 is covered in the book. It is out of the way, and the reader can get to it if they want to.  ES2015 brings in some nice features, so the reader will eventually get to it.  So that is where the book should focus on putting ES2015 learning items and encourage the reader to make changes on their own.

**Comment by asianfilm** [comment]
I'm in that group who is coming to Ember from Rails and who has always avoided JavaScript. I was impressed how some of the ES2015 features made the JavaScript code more straightforward. So, paradoxically, it made the Ember learning curve less steep for me. Take, for example, the last code sample in the Computed Property Macros section of the ES2015 chapter that "is now extremely clear, it almost reads like English text". And with Ember's use of modules, we're already using ES2015 features.

**Comment by balinterdi** [comment]
Yes, good point, Stephen. I'm not sure how typical your use case is. I fully agree that (most) ES2015 features, if applied judiciously make code easier to read but it is surely another thing to learn for most people, and I'm not sure how many from them share your (my) opinion.

What I absolutely don't want is to distract readers from the core Ember concepts in the beginning chapters but I might smuggle little snippets of ES2015 here and there as I go along, just explaining each of them with a couple of sentences.

I think the more popular and widely used ES2015 features become, the more sense it makes to integrate it into the book, too, and gradually "eat up" the ES2015 chapter (well, the computed property macros stuff would remain).

**Comment by asianfilm** [comment]
The "eat up" strategy sounds like a good one. I'm also in the group that reads introductions to books, so you can always encourage people like me to dip into the ES2015 chapter early if they're new to JavaScript. I wouldn't presume that I'm in any majority of your readers.

I also dipped into the Deployment chapter early, because I like to not see deployment as a hurdle later on. I've had consistent problems with getting Pagefront working reliably - but to be fair, (1) in in China and the Great Firewall may be messing with it, and (2) it's in Beta - but Heroku worked a dream.

So, how about just calling the Deployment and ES2015 chapters "Appendices", and encouraging readers to dip into them at any stage and not just at the end of their learning. Same perhaps for Ember Add-On chapter, although that's clearly something one wouldn't want to necessarily dip into early on.

**Comment by balinterdi** [comment]
The resolutions stuff is now very briefly explained in the book and I'll consider the higher level stuff (how to drip ES2015 features and whether to make more complex topics into Appendices).

@asianfilm Thank you for your insights, I really appreciate it.
