### ISSUE TITLE
Instructions on updating Ember-CLI

### ISSUE THREAD

**Issue by asianfilm** [balinterdi/rarwe-issues#155]
The book has instructions on how to install Ember-CLI. I think it should also give instructions on how to update Ember-CLI from a previous version. I'm always having to Google for this. Or else link to the instructions here: https://github.com/ember-cli/ember-cli/releases. Plus, the Github instructions also tells one how to get the latest pre-release version, which is reflected in your `ember -v` output.

**Comment by balinterdi** [comment]
Thank you!
