### ISSUE TITLE
Error: You should not call `create` on a model.

### ISSUE THREAD

**Issue by stephaniehobson** [balinterdi/rarwe-issues#157]
Page 86, in the examples line 13 triggered the error "Error: You should not call `create` on a model. Instead, call `store.createRecord` with the attributes you would like to set." for me. 

I'm not working 1:1 with the same code (I'm trying to adapt it to my use case) so it's possible this was my mistake. I fixed it like this:

```
this.store.createRecord('band', { name: name });
```

The book has been an invaluable resource for me. It is truly excellent!

**Comment by balinterdi** [comment]
Thank you, Stephanie, I am glad you like the book!

Regarding the error, it [comes from Ember Data](https://github.com/emberjs/data/blob/master/addon/-private/system/model/model.js#L804) and the referenced page is before we introduce ED so I'm relatively certain it was not me :) Our models at that point are just `Ember.Object`s, which can be created by calling `create` on the class.

**Comment by stephaniehobson** [comment]
Ah, okay, cool. I will just be pleased I was able to fix it on my own as well as breaking it on my own ;)

**Comment by balinterdi** [comment]
;)
