### ISSUE TITLE
Where to place ajax-loader.gif

### ISSUE THREAD

**Issue by fknoll** [balinterdi/rarwe-issues#158]
@balinterdi 
Chapter: 13, Loading and error routes
Page: 234 (242 i PDF)
File: app/styles/app.css
Line: 24
```
.spinner {
background: url('/images/ajax-loader.gif') no-repeat;
...
}
```

As far as I read the text, I do not find any talk about:

1) where to get the file ```ajax-loader.gif```?
2) where to place this gif file in the Ember CLI project structure?

On page 13 (page 20 i PDF) you mention:
*"The contents of the ```public``` folder are going to be copied with the same path and the same content to the final build. Fonts, images, and a sitemap are good candidates to be placed here."*

So, I googled a nice looking ```ajax-loader.gif``` and placed it in folder ```rarwe\public\images```. That works fine :smile:

**Comment by balinterdi** [comment]
Thank you, Freddy, for raising this. I have this sitting on my todo list for some time but now you've given me a push to do something about it. The spinner I use is available [here](https://s3-eu-west-1.amazonaws.com/rarwe-book/ajax-loader.gif) and also referenced in the next book edition, of course.
