### ISSUE TITLE
Styles not loaded

### ISSUE THREAD

**Issue by gokulk13** [balinterdi/rarwe-issues#159]
At the end of chapter 3, we will be adding styles by Bootstrap by running the command `ember install ember-bootstrap`,. My app doesn't look bootstraped. It looks as such. when I'm trying to load bootstrap manually in HTML file - index.html, it changes the style to an extend, not as shown in the screenshot. My final output after adding styles in style.css is something like the image I have attached.
![rocknroll 2016-02-03 11-25-52](https://cloud.githubusercontent.com/assets/15158776/12775276/beb35028-ca72-11e5-9214-93dc08287ed6.png)

**Comment by balinterdi** [comment]
Have you tried restarting your `ember server` after installing the add-on?

**Comment by gokulk13** [comment]
Yes... I have.. 
Its still

![rnr](https://cloud.githubusercontent.com/assets/15158776/12775716/2529d6b2-ca76-11e5-802a-e04ce8924c60.png)

**Comment by gokulk13** [comment]
Sorry for the inconvenience, I have done a mistake. It's working perfectly now.

**Comment by gokulk13** [comment]
@balinterdi, Please have a look at page 35 of the recent edition. The screenshot looks bootstrapped but we have included the appropriate code for that in page 44. This was the reason, why have confused. Please let me know if I'm wrong at any point.

**Comment by balinterdi** [comment]
Thank you, that was actually an issue, I rearranged a few things and retook screenshots to make sure they match the development of the app in the book.
