### ISSUE TITLE
Make sure the latest (beta) ember-cli version is installed

### ISSUE THREAD

**Issue by gdavdov** [balinterdi/rarwe-issues#162]
Following the instructions in chapter 2 the current version installed by:
`npm install -g ember-cli`
is 1.13.15, rather than the current beta. I checked the npm page and that's the latest release. How should this be handled?
```
ember -v
version: 1.13.15
node: 5.4.0
npm: 2.14.10
os: darwin x64
```

**Comment by gdavdov** [comment]
Looked through some closed issues (sorry, forgot to check that before opening the issue), and it looks like this may be referenced elsewhere, in particular https://github.com/balinterdi/rarwe-issues/issues/155 seems to have a solution. It would be good to see that in the book.

**Comment by balinterdi** [comment]
Thank you, that's a great catch. If `npm install -g ember-cli` installs the latest stable one (`1.13.15`) the instructions should say `npm install -g ember-cli@latest`.

**Comment by balinterdi** [comment]
Fortunately Ember CLI 2.3.0 is now officially stable (no more betas), so there is no longer a difference between the latest and the stable version.

I've updated the command to be `npm install -g ember-cli@latest`. Thank you!
