### ISSUE TITLE
Chapter 8: Controllers : Smooth UI Flows

### ISSUE THREAD

**Issue by zzr994** [balinterdi/rarwe-issues#163]
When a new band  is created, the blog ""There are no songs yet. Why don't you create one?" is shown. If the user clicks on the link, then the user can add a new song. This works fine, but I encountered an issue while adding a second new band.

I think this is because When the first song is being added to the new band, the 'songCreationStarted' property in the app/controllers/bands/band/songs.js is set to true.

But once a new song is created, we should reset this property back to 'false". Right?
Otherwise if another new band is created, we do not see the blog. 
I had to add the following change to the createSong() actions method in the songs route

// app/routes/bands/band/songs.js
    (....)
    actions: {
        /**
         * createSong()
         */
        createSong: function() {
	   (...) 
           controller.set('songCreationStarted', false); 
        },

**Comment by balinterdi** [comment]
Thank you, you spotted a very tricky bug that I wrote about in length a while ago on my blog:

[Controllers are singletons](http://balinterdi.com/2014/06/26/ember-gotcha-controllers-are-singletons.html)

Nevertheless, I need to still fix it in the RARWE app. For the record, I'll use the `resetController` hook in the route to fix it, probably in the Advanced routing chapter.

**Comment by balinterdi** [comment]
Taking a thorough look at this, this was already fixed on Dec 07, 2015 and was subsequently included in the 20160121 update of the book. It appears on page 136, in the section called "Resetting controller properties".
