### ISSUE TITLE
Reading on Kindle

### ISSUE THREAD

**Issue by ThomasSchoenbeck** [balinterdi/rarwe-issues#167]
It is not the easiest book to read on a kindle device as the text is gray. It looks dusty and while reading it doesn't feel right.

Is there a way to change the .mobi version to use the color black for normal text instead of gray?

**Comment by balinterdi** [comment]
Hey Thomas,

Thank you very much for reporting this. I've now uploaded the mobi to my Kindle and I see what you're talking about, this should be improved. At one point I checked this and the text was black but it seems like the black has now faded :)

**Comment by balinterdi** [comment]
So I just updated Gitbook (the software I use to create the epub and mobi versions) to the latest stable one, and created the mobi version. Text is black again but highlighting in code snippets is not ideal (although I wonder if this could be done better in black-and-white). I can send you a link to download that version if you give me your email address or you can wait for the next book release that should happen next week.

**Comment by ThomasSchoenbeck** [comment]
Hi there,

thanks for the quick reply. I would love to grab the new version already as
I am currently reading it. You can send me the link to
thomas.schoenbeck@web.de .

I think the text for the highlighting in code snippets is fine. It was just
a bit odd to read a complete page in gray.

Thanks again, and best regards, Thomas.

**Comment by ThomasSchoenbeck** [comment]
Some comments to the new provisional version.

* normal text is now black and better readable
* my kindle now shows the cover of the book. not sure if this should have worked before, I now did send the book via mail to my kindle, the version before was copied via cable and windows explorer
* Table of Contents got messed up, Text is bigger, more spacing between lines
* Headlines have a bigger top margin now

I am not sure if I should close the issue already. Maybe I could add more findings later. But apart from this, the reported issue is resolved.

**Comment by ThomasSchoenbeck** [comment]
Issue with the gray text is resolved. Normal text (not those syntax sections) are black now.
