### ISSUE TITLE
Diff for routes/bands.js might be confusing

### ISSUE THREAD

**Issue by jluckyiv** [balinterdi/rarwe-issues#171]
In the first code listing for `routes/bands.js`, there are diff `+` marks for `var Song`. In the next listing, there are `+` marks for `var daughter`. Although I've worked through the book several times, a first-time reader might not realize, that the "seed" data must be copied to `routes/bands.js` and there should be additional code. 

I suggest that the first code example, following "let's adapt our code to the now existing relation between `Band` and `Song`" include the seed data as well as the `Song` definition. Also, because "now existing" is [compound modifier](https://en.wikipedia.org/wiki/Compound_modifier#Hyphenation_of_elements), I suggest it be changed to "now-existing."

The next paragraph should read 

> We simply brought over the definition of the `Song` class **and the "seed" data** from the `songs` route. 

After that, the additional `routes/bands.js` code sample could remain as written, or slightly truncated with just enough code (maybe just the previous song) to give context to `var daughter`.

**Comment by balinterdi** [comment]
Very good point, I made it so.
