### ISSUE TITLE
Chapter 7 : Components : Closure actions

### ISSUE THREAD

**Issue by zzr994** [balinterdi/rarwe-issues#173]
The text says:

"Instead of storing the action name to trigger in the setAction attribute, we now have an action function to
be called in the on-click attribute of the component. The component's set action handler needs to reflect
that change."

I am wondering if this is correct? Should it be sendAction instead of setAction?

**Comment by balinterdi** [comment]
Yes, this is correct. I'm passing the name of the action to be invoked as an attribute of the `star-rating` component (on page 98):

```handlebars
{{star-rating ... setAction="updateRating"}}
```

The action will be fired by calling `component.sendAction('setAction', ...)` (on page 104). This will look up the `setAction` attribute on the component and trigger that action (which is `updateRating`). I think what might be confusing is that `sendAction` and `setAction` sound so similar, so I'll probably come up with a name that is easier to discern cognitively. Thank you!

**Comment by zzr994** [comment]
Thanks for the clarification, now I understand the text and I agree with the explanation.
You are referring to the "setAction" attribute in the star-rating component.

I wonder why you call this as "attribute" of the star-rating component.
Is it not the "property" of the star-rating component?
As per the earlier text in the chapter it is a property. See the text below.
"rating, maxRating, item and setAction are custom properties that are not rendered...."

Yes, I agree that the naming convention definitely adds to the confusion and it was going to be my follow up comment. But since you also recognized the need to rename some of the actions, 
my feedback/suggestions are as follows:

Since "set" is a generic name, extend the name to tell what it is setting.
Since these are all in the "actions" block, there is no need to append the names with "Action".

The components->star-rating.js->actions->set is a very generic name.
Suggest to rename the "set" action on the component to "setStarRating".
This means that this method will change the star rating on the component.

The external context action that receives updates from the component.
Suggest to rename the "setAction" property to "updateStarRating" rating.
This means that this property represents the external context method when called will update the external context with the changes.

I read in the other comments that you have updated this chapter for the next revision of the book. I will be happy to review it if you want.  Otherwise I will wait for the next revision of the book.

**Comment by zzr994** [comment]
Notice how the component is created from the template:

{{star-rating item=song rating=song.rating setAction="updateRating"}}

"It is also important to know that passed-in values that are unquoted will establish a binding between the property from the context and the property of the component. Above, the rating of the component is assigned song.rating (which is the rating of the song) and a two-way binding is created between the two. Should either end change, the other will change accordingly."

Which means that when the star-rating component updates its internal rating, the external song.rating is also changed automatically.  So it is not necessary for the component to communicate this information via external communications.  The external update however could be used for other purpose such as indicating to the context that the rating was modified.

**Comment by balinterdi** [comment]
First of all, thank you for your great and detailed feedback.

> I wonder why you call this as "attribute" of the star-rating component.
Is it not the "property" of the star-rating component?
As per the earlier text in the chapter it is a property. See the text below.
"rating, maxRating, item and setAction are custom properties that are not rendered...."

Property is the general name, attribute designates the properties of the component that can be passed in (and thus customize its behavior). However, in this case, all those that I listed are attributes, so I'll need to amend the text, thank you.

I'd already made some modifications in the chapter and decided to call the external action name "on-click", so there is no renaming when I switch from old-style to closure actions. Now, based on your feedback, I decided to rename the internal action name to "setRating".

**Comment by balinterdi** [comment]
> Which means that when the star-rating component updates its internal rating, the external song.rating is also changed automatically. So it is not necessary for the component to communicate this information via external communications. The external update however could be used for other purpose such as indicating to the context that the rating was modified.

True, I *could* modify the rating attribute in the component and it would also change the song's rating but I'm not doing that because in most cases it's better to have a uni-directional data flow, called DDAU (Data down actions up) in Ember (see Mistake #8 [in my Toptal blog post](https://www.toptal.com/emberjs/the-8-most-common-ember-js-developer-mistakes)). I'm probably not emphasizing this enough in the book, however.

**Comment by zzr994** [comment]
I read your post about DDAU.  It was very informative. Now I understand this better and will help me avoid such mistakes. Thanks for pointing this out.
