### ISSUE TITLE
I can't tell what version of the book I have

### ISSUE THREAD

**Issue by g--** [balinterdi/rarwe-issues#174]
My suggestion is putting some sort of version identifier at the beginning of the book so we can easily tell which is which in our e-readers (and delete the old versions)

Cheers!

**Comment by balinterdi** [comment]
Hey Geoff,

Definitely, this would make a lot of sense. I'll come up with something, thank you for bringing it up. Are you reading it on a Kindle?

**Comment by g--** [comment]
I'm reading an epub in iBooks.

You could emulate https://en.wikipedia.org/wiki/Cataloging_in_Publication .. even if you don't register with the library of congress (or similar organization), it still might be useful to have the publication case and basic information (like your name and website).
