### ISSUE TITLE
diff flag may be incorrect : Chapter 7: Components | 94

### ISSUE THREAD

**Issue by jellycow** [balinterdi/rarwe-issues#178]
in the code panel, "on-click": null, is marked with a  red - (to be removed) but is the new bit of code needed to be added for the example. Should be marked with green +

![page 94 - diff example](https://cloud.githubusercontent.com/assets/209072/15015866/225bcf6c-1206-11e6-9636-5d402681b5bc.jpg)

**Comment by balinterdi** [comment]
Thank you very much for this and the two other issues you reported. Great catches, I've fixed all of them!

**Comment by jellycow** [comment]
Not a problem, very much enjoying working through the book

**Comment by balinterdi** [comment]
Reopening for other people to see to prevent double-reporting.
