### ISSUE TITLE
Bug (in npm?) is installing the wrong version of liquid-fire

### ISSUE THREAD

**Issue by jshwartz** [balinterdi/rarwe-issues#180]
Not really the fault of the book, but installing liquid-fire threw an error because npm, for some reason, was installing an outdated version. I'm sure most people will figure this out for themselves with some quick googling. But you need to update the version in the package.json file to the recent version "liquid-fire": "0.23.0" then run "npm install".

**Comment by balinterdi** [comment]
Interesting, I just did `ember install liquid-fire` in an Ember app and it installed version `0.23.1`, the most recent one. Is it possible that you had an older version of `liquid-fire` npm cached? npm and bower caching can play tricks on us, Ember devs.

**Comment by jshwartz** [comment]
Hmm, nope, never used liquid-fire before - who knows, I figured there was a
good chance it was just me.

**Comment by balinterdi** [comment]
npm surprises can come in many form.
