### ISSUE TITLE
Accesing model object from console in chapter 3

### ISSUE THREAD

**Issue by gandra** [balinterdi/rarwe-issues#182]
Hi.

I am just starting to read a book and very soon I have experienced some problems.
I can not access model object(chapter 3) from console using:
`var blackDog = $E.get('firstObject');`
See [http://i.imgur.com/JpzwNhv.png](http://i.imgur.com/JpzwNhv.png)

Anyway I have succeed to do it with following command from console:
`$E._controller.model.get('firstObject');`

and this command for setting property:
`$E._controller.model.get('firstObject').set('title', 'New title from console');`

I am using `Google Chrome version 50.0.2661.94 m`

So eventually this can be updated in the book.

**Comment by balinterdi** [comment]
That shouldn't be necessary. I started from scratch and followed the book and it seems to work for me:

![screen shot 2016-05-12 at 21 15 10](https://cloud.githubusercontent.com/assets/5022/15227284/b57cb690-1886-11e6-8952-963d35133ebb.png)

Is it possible that you didn't click the `$E` in the Model column of the Ember Inspector?

**Comment by gandra** [comment]
I have clicked $E. Before clicking on $E I couldn't run 
`$E._controller`

**Comment by balinterdi** [comment]
Sorry, I was ambiguous. I meant to ask whether you clicked the $E *in the Model column*, so the emphasis is clicking on the right $E. We have the same version of Ember, and probably the same version of Ember Inspector so I don't know what else can go wrong.

**Comment by gandra** [comment]
I have checked all options:

1. I have clicked the $E in the Model column - NOT WORKS
2. I have clicked the $E in the View/Component column - NOT WORKS
3. I have clicked the $E in the Controller column - WORKS!!!

Seems logical since controller is responsible to hold model?

**Comment by balinterdi** [comment]
Well, it's the model that is an array and that a `firstObject` property. If you take the controller, the path to get to the first object in the model should be `$E.get('model.firstObject')`, so I still don't understand but I'm happy it works.
