### ISSUE TITLE
Calling property on a function with the dependent keys as parameters explanation

### ISSUE THREAD

**Issue by gandra** [balinterdi/rarwe-issues#185]
At the end of the page 61 we can see:

> There is another way to define CPs that leverages extending the prototype of Function:

then, on the beggining of the page 62, goes code code snippet and then:

> Calling property on a function with the dependent keys as parameters transforms a function into
> a CP. However, this syntax is now discouraged as extending the prototype of core JavaScript classes
> is frowned upon. You will still find abundant examples of it, though, so it's useful to be able to
> quickly parse it.
> 

Reading all this assumes code snippet on page 62 is different from previous one(on page 59).
Neverthless I can not found difference(except console.log), so or it is a error in snippet or I have misunderstood it.

Question is where is this `syntax ` difference?

**Comment by balinterdi** [comment]
Thank you very much, I was over-eager in replacing old-style CP declarations with the new idiom and replaced even the one instance I'd have had to keep :)
