### ISSUE TITLE
Unclear creation of songs route

### ISSUE THREAD

**Issue by gandra** [balinterdi/rarwe-issues#186]
On the page 63 is stated that route songs is not generated and there is call to execute command to generate route:
[http://i.imgur.com/aeR7LsW.png](http://i.imgur.com/aeR7LsW.png)

Anyway,
on the page 53 this route has been already defined:
[http://i.imgur.com/G9vr8Q6.png](http://i.imgur.com/G9vr8Q6.png)

So,
this part is not clear. Should be improved.

**Comment by balinterdi** [comment]
On page 50, it's the `bands.songs` route that is defined in `app/router.js`, and on page 63 it's `bands.band.songs`, so it's not the same route but on page 52, the `bands.band.songs` route is created in the router so this can indeed by misleading.

I've improved the explanations (and now do not suggest to generate the `bands.band.songs` route) to avoid confusion.

Thank you for pointing that out.
