### ISSUE TITLE
Adding a CSS class to stars bump

### ISSUE THREAD

**Issue by Bogeyduffer** [balinterdi/rarwe-issues#188]
On page 272 you mention "We haven't used this.inHelper yet. It matches a transition that was observed by the helper that we pass to it, in this case, liquid-bind. As we currently have only one instance of that helper, this will work, though it might be prudent to add a css class and then use this.hasClass(...), just as we did for the band's description textarea in the previous section."

I thought I'd try to do this just to help me understand it. But, being a bit of a novice at this, I was not able to figure out how to make it work. I get an error about closing the statement before the "class" code. Below are the steps I took for this. I think that I just don't know how to define the "class" within that statement. The error is shown at the end below. Can you help clarify this? 

Thanks.
Bob

For the band description you go from {{#if isEditing}} to {{#liquid-if isEditing class="band-description"}} in the .hbs and in the transitions.js you used "this.hasClass('band-description')", 

I tried to add the class to the stars rating by changing the first line in the .hsb from:

```
{{#liquid-bind stars as |liquidStars| }}
  {{#each liquidStars as |star| }}  
  <span class="star-rating glyphicon {{if star.full 'glyphicon-star'
'glyphicon-star-empty'}}"
    {{action "setRating" star.rating}}>
</span>
{{/each}}
{{/liquid-bind}}
```

to:

```
{{#liquid-bind stars as |liquidStars| class="star-rating"}}
  {{#each liquidStars as |star| }}  
  <span class="star-rating glyphicon {{if star.full 'glyphicon-star'
'glyphicon-star-empty'}}"
    {{action "setRating" star.rating}}>
</span>
{{/each}}
{{/liquid-bind}}

```
and modified the transition.js from:

```
 	this.transition(
          this.inHelper('liquid-bind'),
          this.use('slight-scale')
 	);
```

to:
```
 	this.transition(
          this.inHelper('liquid-bind'),
          this.hasClass('star-rating'),
          this.use('slight-scale')
 	);

```
The error I get:

```
Error: Parse error on line 4:
...quidStars as |star| class="star-rating"
-----------------------^
Expecting 'CLOSE', got 'ID'

```

**Comment by balinterdi** [comment]
Oops, that's a syntax error, the `|liquidStars|` should be at the very end, so it should be:

```handlebars
{{#liquid-bind stars class="star-rating" as |liquidStars|}}
  (...)
{{#/liquid-bind}}

Let me know if that doesn't fix it for you, and thank you for spotting this.

**Comment by Bogeyduffer** [comment]
Okay, Thanks.

I thought about that. Just wasn’t sure and too much of a novice I guess to go ahead and try it. I’ve gotten beyond that point. But, I may go back and try it again.

I finished your book last night. I thought it was great. Certainly one of the best tutorials I’ve read. Like someone else said, It will be like a bedside bible. Thanks for taking the time to write it.

Now I just have to put it all to use.

Thanks, 

Bob

**Comment by balinterdi** [comment]
Thank you very much, Bob! Words like this keep me going.
