### ISSUE TITLE
Snapshots of code according to chapters

### ISSUE THREAD

**Issue by gandra** [balinterdi/rarwe-issues#190]
It would be nice to have tags for each chapter.
For example:
ch_01
ch_02
ch_03

In such way we could easily check our code against repo.
I have bought  middle package and give 20$ more expecting to check the code against repo.
Now I have finished chapter 07 and have code not working. I have error in the console:
[http://i.imgur.com/a3P72RO.png](http://i.imgur.com/a3P72RO.png)

How I can find snapshot of code in your repo for chapter 7?

**Comment by balinterdi** [comment]
The code repository has tags for each chapter, named for the chapter they implement. Please follow [the code repository's README](https://github.com/balinterdi/rarwe-code/blob/master/README.md) to see how.

**Comment by gandra** [comment]
Thanks.
