### ISSUE TITLE
Chapter 4 : Routing : Application Route

### ISSUE THREAD

**Issue by zzr994** [balinterdi/rarwe-issues#191]
Hi,

The text reads as follows.

"Having the router activate the application route on all requests gives us a place to define operations that
are necessary for the whole application. This might include choosing the language for the site, or fetching
data that is needed to render a layout that's common across the pages of the site."

Let us assume that we need to get the language for the site from the server.  Will this be one time fetch? I would be concerned if this piece of data is fetched more than once for the life span of the application.

Let me use an example.
1. http://localhost:4200/bands/perl-jam/songs
2. http://localhost:4200/bands/led-zeppelin/songs

We start from looking at the songs from "perl-jam".  At this time we transition through the application route and we fetch the language for the site from the server.  We then switch to looking at songs from "led-zeppelin".   Does the transition go through the application route again?

After reading the "Skipping Model Resolution" in the Advanced Routing the most likely answer to this question would be "no".  But I am not entirely certain.  

Hope to get some more clarification on this subject and possibly enhance the application to include a feature for fetching some information that is common to the entire application (such as getting the title of the application from the server instead of hard coding it).

Thanks.

**Comment by balinterdi** [comment]
Very good question. Yes, your assumption is correct, the transition doesn't go through the application route the second time around, so it's a good place to fetch the site's language (or title).

I'll leave this open until I explain this better in the Nested routes chapter, and possibly adding a feature that leverages this, as you suggest.

**Comment by zzr994** [comment]
Thanks for the response. Looking forward to the updates.

**Comment by balinterdi** [comment]
I've now added the below text to clarify this:

> It is important to note that this full, top-down transition is only triggered
when the app initially loads. If the user subsequently navigates to a route (via
`link-to`), the router will make the transition directly, not descending through
the parent routes on its way.

> That also means that fetching data you only want to fetch once can be placed in
the top-most, application route. We can be assured that this route, and thus the
data fetching operation, will only happen once.
