### ISSUE TITLE
Linke to Encore section doesn't work on page 85

### ISSUE THREAD

**Issue by gar** [balinterdi/rarwe-issues#193]
Minor issue, but the link to "Encore" doesn't work on page 85 (at the end of the sentence "(classNames is a concatenated property. You can read more about them in the Encore."). Sentence is also missing closing parenthesis :)

I'm using Preview on OS X in case it makes a difference, but the other links to "Encore" worked for me (e.g. on page 32).

**Comment by balinterdi** [comment]
Thank you, Gar.
