### ISSUE TITLE
Chapter 8: Controllers (page 100) - Diff signs not formatted correctly in bands template

### ISSUE THREAD

**Issue by gar** [balinterdi/rarwe-issues#194]
The diff signs on the code listing on page 100 seem to be formatted incorrectly (line 7 just starts with `+++`):

<img width="850" alt="screen shot 2016-06-02 at 16 34 12" src="https://cloud.githubusercontent.com/assets/16580/15750969/41523a82-28e0-11e6-8287-96ccb0d17f8b.png">

**Comment by balinterdi** [comment]
This is fixed and will go out in the next release.
