### ISSUE TITLE
Capter 13 (page 227): Removed line in diff is the same as added line

### ISSUE THREAD

**Issue by gar** [balinterdi/rarwe-issues#195]
Another little nitpick (I hope these are useful and not annoying!)

The diff on page 227 has a line removed (line 16) which is the exact same as the line added (line 17):

<img width="552" alt="screen shot 2016-06-05 at 16 20 21" src="https://cloud.githubusercontent.com/assets/16580/15806365/c12bcd08-2b39-11e6-8870-530f11d43938.png">

I think the removed line should be `return this.store.findAll('band');` instead.

**Comment by balinterdi** [comment]
Hey Gar,

Fixed, thank you very much. No, they are not annoying, quite the contrary!
