### ISSUE TITLE
Chapter 3 (page 18-19): Missing application.hbs

### ISSUE THREAD

**Issue by wbeeftink** [balinterdi/rarwe-issues#196]
Hi Balint, the current version of ember-cli (2.6) doesn't generate an application.hbs anymore. It adds the ember-welcome-page package to show a welcome page instead.

It was easily fixed by removing the package (as suggested on the welcome page) and adding the handlebars template myself but it might confuse new readers.

**Comment by balinterdi** [comment]
Hey Wouter,

Thank you very much for pointing that out, I've missed this. I've now rewritten that section to work with ember-welcome-page (uninstalling the package one step later, as you suggest it).
