### ISSUE TITLE
Should the book be using Mirage instead of Pretender?

### ISSUE THREAD

**Issue by cafreeman** [balinterdi/rarwe-issues#197]
I (think?) I've got the latest version of the book. I downloaded it from Gumroad (the file is `rock-and-roll-with-emberjs-20160503`) but I just got to the testing chapter and it's setting things up using Pretender. If that's intended, then it's totally fine, but the demo app [here](http://balinterdi.com/2016/02/26/rock-and-roll-with-ember-dot-js-demo-a-public-ember-dot-js-example-project.html) highlights the fact that it uses Mirage so I'm a bit confused.

If there *is* a version that uses Mirage, I definitely want to make sure I download it since that'd be a great thing to learn. Am I just looking in the wrong place?

**Comment by balinterdi** [comment]
Hey Chris,

Yes, this is somewhat confusing, my fault. There are two versions of the Rock & Roll app. The first is the one we develop in the book and it uses Pretender. The second is a largely reduced version of the full application, and I call it the "demo version". It is [open source](https://github.com/balinterdi/rarwe-demo) and uses Mirage.

On the longer term, I want to convert the full app to use Mirage, too. Incidentally, I have a blog post that is coming out soon that talks about Mirage in more detail.

**Comment by cafreeman** [comment]
Ahhh, ok. I understand now. Thanks for the clarification :) Definitely looking forward to that blog post!

I'll go ahead and close this.
