### ISSUE TITLE
Chapter 3: Templates and data bindings, p. 28

### ISSUE THREAD

**Issue by mikemckenna** [balinterdi/rarwe-issues#198]
This is my first ever issue filed on Github. So apologies if I didn't follow correct protocol. 
There is a typo in code for Song object - comma after band not rating. (2016/7/7 Book Edition)

book has:

```javascript
var Song = Ember.Object.extend({
  title : '',
  band: ''
  rating: 0,
});
```

should be 

```javascript
var Song = Ember.Object.extend({
  title : '',
  band: '',
  rating: 0
});
```

**Comment by balinterdi** [comment]
Thank you, Mike, great catch!
