### ISSUE TITLE
Any effort going to be spent on explaining testing?

### ISSUE THREAD

**Issue by jsmestad** [balinterdi/rarwe-issues#20]
This may be in a latter chapter, and I am only in Chapter 8, but I find it odd that we are using `ember generate` for everything which generates test files. However up to this point there has not been any mention of testing, these files, etc.

I think its acceptable to approach the project as you have, I realize though doing any of this in a 'production app' would require additional reading on how best to test things like advanced routing and controller actions.

**Comment by balinterdi** [comment]
Chapter 11 is dedicated to testing, both acceptance and unit (we write tests for the star-rating component).

I've also pondered whether it's best to generate everything and have a handful of generated unit tests lying around (which still pass, fortunately). I opted for consistency and generate everything except a few places where I explicitly state that a file is created manually.

**Comment by jsmestad** [comment]
Ah cool; yeah maybe a call out that its dealt with in a latter chapter somewhere at the start.
