### ISSUE TITLE
Chapter 5: Nested routes, p.59

### ISSUE THREAD

**Issue by mikemckenna** [balinterdi/rarwe-issues#201]
When updating `//app/routes/bands.js` book has:
```javascript
var Band = Ember.Object.extend({ 
  name: '',

  slug: Ember.computed('name', function() { 
    return this.get('name').dasherize();
  }), 
});
```

should it be? (add songs array & remove trailing comma from slug cp):

```javascript
var Band = Ember.Object.extend({ 
  name: '', 
  songs: [],

  slug: Ember.computed('name', function() { 
    return this.get('name').dasherize();
  })
});
```

Apologies, if these little things are too minor. Just thought would submit as I go through the book learning.

**Comment by balinterdi** [comment]
Thank you, just fixed this, no need to apologize, these are really valuable!
