### ISSUE TITLE
Page 46, Chapter 4 - Route typo

### ISSUE THREAD

**Issue by jacobarriola** [balinterdi/rarwe-issues#203]
The class name `Routes` for what's left in `app/routes/application.js` seems like a typo. I believe it should be singular, `Route`.

Current:
```
export default Ember.Routes.extend({
});
```

Expected:
```
export default Ember.Route.extend({
});
```

Thanks!

**Comment by balinterdi** [comment]
Thank you, Jacob, I've fixed this.

**Comment by jacobarriola** [comment]
Great! Thanks!
