### ISSUE TITLE
p. 110 & 111 - chapter 8 - missing diff signs

### ISSUE THREAD

**Issue by andyhelmsworth** [balinterdi/rarwe-issues#206]
Code sample on page 110 has no diff signs, and could really use them. 

`+` Line 5 is a brand new line - `<form>` tag
`+` line 7 adds the `type="submit"` property to the `<button>` tag
`-` between lines 8 and 9, the `{{action "createBand"}}` handler is removed
`+` Line 9: `</form>` 

Everything after line 10 could be truncated under an ellipse, as in previous samples.

Page 111 has the same issue:

`+`  `<form ... >` in line 5 is new
`+` line 7 adds the `type="submit"` property to the `<button>` tag
`-` between lines 7 and 8, the `{{action "createSong"}}` handler is removed
`+` Line 9: `</form>`

**Comment by balinterdi** [comment]
I think this is done for both of these:

![screen shot 2016-08-14 at 14 45 23](https://cloud.githubusercontent.com/assets/5022/17649162/caa05734-622d-11e6-9bd3-640678351dd6.png)
![screen shot 2016-08-14 at 14 46 05](https://cloud.githubusercontent.com/assets/5022/17649164/dadc86b8-622d-11e6-90f1-9999946e9560.png)

Let me know if I misunderstand something.

**Comment by andyhelmsworth** [comment]
Yup, looks like it is. As I mentioned in issue #205 it looks like you have released a new version since I downloaded. Closing this.

(P.S. technically line 9 in example two needs a `+` , not to be too nitpicky.)
