### ISSUE TITLE
pp. 69 & 125 - app/templates/bands/band.hbs

### ISSUE THREAD

**Issue by andyhelmsworth** [balinterdi/rarwe-issues#208]
On page 69, the sentence directly before 'The road says' section reads:

>  Consequently, the bands.band template above can be deleted, and the app
will continue working just as before.

I would argue this sentence should be amended to warn against doing this, as the template is used later, on page 125. I hope this isn't nitpicky, but apparently I decided to go ahead and delete the template, only to get confused when I was asked to modify a nonexistent file. 

Obviously, it's your call whether this merits modification or not, but I thought I'd run it by you based on my experience - cheers.

**Comment by balinterdi** [comment]
Thank you, Andy. I'm on vacation until 08/07 but this definitely seems like an issue and I'm going to fix it when I'm back.

**Comment by balinterdi** [comment]
Thank you, Andy, great catch.

I modified the text to not prompt readers to delete the template on page 69.

**Comment by andyhelmsworth** [comment]
Thanks for the change, Balint! I'll let you close this when you're ready since I don't want to mess up your workflow. Cheers :)
