### ISSUE TITLE
p. 141 - Chapter 10 - Seed data

### ISSUE THREAD

**Issue by andyhelmsworth** [balinterdi/rarwe-issues#209]
Code snippet on p. 141 needs a `-` diff sign on line 8, which reads:

> // Delete all seed band and song creation code from here

Since the book's code formatting renders comments in such a pale grey, that was easy to miss, and broke the application. I should have known better, given the contents of the first paragraph on that page, but I still think it would be helpful to future readers. Cheers!

<hr />

P.S. This doesn't break anything, but on the same page, line 3 of snippet:
`import Band from 'band';`
looks like it should have a `-` as it is absent from later examples of that file, and throws a 'defined but never used' from JSHint/Lint.

**Comment by balinterdi** [comment]
Hey Andy,

Thank you for this.  I've fixed your second example. In the first one, do you mean there should be a `-` in front of the comment line (`// Delete all seed band and song creation code from here`)?

**Comment by andyhelmsworth** [comment]
Thanks for fixing the second one. Regarding the first, yes, that's what I meant. Just to call the reader's attention to the fact that something needs deleting. But of course it's your call :)

**Comment by balinterdi** [comment]
Turns out I'd already done that based on your suggestion, changing the line to `// All band and song creation code was here` and adding the `-` in front: `- // All band and song creation code was here`.

**Comment by andyhelmsworth** [comment]
Sounds good, thanks much!
