### ISSUE TITLE
Chapter 10

### ISSUE THREAD

**Issue by jsmestad** [balinterdi/rarwe-issues#21]
### Page 126

You show a snippet of what "Creating a band" looks like now in `app/routes/bands.js" but the line `import Band from '../models/band';` is not there as you instructed on Page 119:

```
Before we start migrating our app to use Ember Data, let's make sure to delete the setting up of seed data in app/routes/bands.js. When using Ember Data, model classes are not instantiated manually, so delete everything between the first line importing Ember and the route object definition:
```

which included the two import statements for `Band` and `Song`

----

### Page 133

    We only have to add a song.save() line to the end of updateRating so that a PUT request
    is sent to the backend for the appropriate song:

It says we only have to add `song.save()` but that is not the case as the snippet contains a new conditional check on the rating. What should be added here? Is this needed?

```javascript
if (song.get('rating') === rating) { 
  rating = 0;
}
```

**Comment by balinterdi** [comment]
Thanks!
