### ISSUE TITLE
p. 142, chapter 10 - Could not find module `band` imported from `rarwe/routes/bands`

### ISSUE THREAD

**Issue by daltonrooney** [balinterdi/rarwe-issues#210]
On page 142, line 3 of the code example is `import Band from 'band';`, however with that I get  `Uncaught Error: Could not find module 'band' imported from 'rarwe/routes/band'`

I had to go back to `import Band from '../models/band';`, which is how it was first set up on page 76.

**Comment by balinterdi** [comment]
Hey Dalton,

Thank you, that indeed was a bug that I've now fixed based on your description.

**Comment by thomas-atwood** [comment]
Hit the same problem 8/13 in a version of the book pdf downloaded recently but apparently prior to the fix.  Thanks for the comment.
