### ISSUE TITLE
$E.get is not a function? (Chapter 3)

### ISSUE THREAD

**Issue by ralbion** [balinterdi/rarwe-issues#211]
Hi,

I am having a problem similar to that in a past issue here: https://github.com/balinterdi/rarwe-issues/issues/182

`$E.toString();
"<Ember.Object:ember398>,<Ember.Object:ember399>,<Ember.Object:ember400>"`
`blackDog = $E.get('firstObject');
VM311:1 Uncaught TypeError: $E.get is not a function(…)`

Yes I am clicking on the $E in the model column, as per the book instructions.

Any ideas?

Thanks in advance,

Ember Inspector 1.10.0
Ember 2.5.1
Ember Data 2.7.0
jQuery 2.2.4

**Comment by balinterdi** [comment]
Could you make a screen recording about how that exactly happens so that I can replicate this? (I use [recordit](http://recordit.co/) but I'm sure there are several others.

**Comment by ralbion** [comment]
So after much messing about... I ended up installing the latest version of Ember and that has resolved it. The thing is, I was trying to use the exact same versions as you had installed according to what I saw in the book (Ember-CLI 2.6.1, Ember 2.5.0) but clearly there was an issue there as the Object Array wasn't being recognised as an Ember object. I have found in the past that Ember tutorials are normally extremely version specific, obviously since it's an evolving framework. Maybe there was a conflict in the version of Ember Inspector?

**Comment by balinterdi** [comment]
Yes, this could be it. I think the Ember Inspector is automatically always updated to the latest version (since it's an extension) but it's still possible that inspecting $E does not always work as it should.

I check that the application works and the tests run after each update but not that the $E works correctly in one of the first chapters.

**Comment by balinterdi** [comment]
The Ember Inspector has indeed changed and I rewrote the relevant section to reflect this.

**Comment by ralbion** [comment]
Ok great. Good to know. Thanks

**Comment by balinterdi** [comment]
Here is the updated section:

```
Once you have installed the extension, open the Developer Tools and you'll have
an Ember tab right beside the default tabs. Click it and select Routes from the
left panel. Next, click `index` in the Controller column and then the $E next
to the `model` property in the right sidebar (you will see the `$E` when you
hover over the model property)
```

[Here is the flow](http://recordit.co/1jlHEAJX2P) showing you how to do it.
