### ISSUE TITLE
p. 227 - Chapter 13 - missing diff

### ISSUE THREAD

**Issue by andyhelmsworth** [balinterdi/rarwe-issues#212]
Hi Balint, hope these issues regarding diff signs are helpful, and not annoying - I can eschew reporting issues of this nature if they are. Anyway, I'm using version 20160708 of the book, and found another section missing diff signs:

Page 227, second snippet, lines 4-12 all need a `+` ; searched the book and I'm 90% sure that's the first instance of that `wait` function. Attached a screenshot if that helps - thanks much!

![p227](https://cloud.githubusercontent.com/assets/14791023/17918392/3f91ff82-6979-11e6-90fe-e461e98fb426.JPG)

**Comment by andyhelmsworth** [comment]
Thanks, Balint! Have a nice day :)

**Comment by balinterdi** [comment]
Thank you, Andy, you, too!
