### ISSUE TITLE
Chapter 16, page 267 - add repository info to package.json

### ISSUE THREAD

**Issue by andyhelmsworth** [balinterdi/rarwe-issues#213]
When I execute the `$ npm link` command at the end of page 267, npm throws 

`npm WARN ember-cli-star-rating@0.0.0 No repository field`

It would be a nice touch, I think, to include a snippet showing us how to add repo info to the package.json file. It's pretty easy to Google, but I'd argue a short code snippet could help. From [StackOverflow](http://stackoverflow.com/questions/16827858/npm-warn-package-json-no-repository-fieldhttp://stackoverflow.com/questions/16827858/npm-warn-package-json-no-repository-field), the snippet would just need to look like this:

`...`
`},`
`"repository": {`
`  "type": "git",`
`  "url": "git://github.com/username/repository.git"`
`},`
`...`

Just my $0.02. Thanks!

**Comment by balinterdi** [comment]
Another great suggestion and is indeed something that I overlooked.

Thank you, Andy, I've fixed it.
