### ISSUE TITLE
Chapter 16, page 261 - spell out navigation out of rarwe directory

### ISSUE THREAD

**Issue by andyhelmsworth** [balinterdi/rarwe-issues#214]
On the bottom of page 261, you have us execute two commands:

`$ ember addon ember-cli-star-rating`
`$ cd ember-cli-star-rating`

When I tried to do this, I was still in the rarwe directory, so ember threw:

`You cannot use the addon command inside an ember-cli project`

I think it would be a nice touch to spell out that we need to `$ cd ../` before executing the above commands, and maybe a sentence or two explaining why that's the case. Thanks!

**Comment by balinterdi** [comment]
Thank you, fixed now.
