### ISSUE TITLE
Line 9 - Chapter 7

### ISSUE THREAD

**Issue by lypborges** [balinterdi/rarwe-issues#217]
Hi, I think it's a simple mistake on pag 97 (PDF) in line 9

> // app/components/star-rating.js
> 
>   this.get('on-click', {item: this.get('item'), rating: newRating});

Should be:

>  this.sendAction('on-click', {item: this.get('item'), rating: newRating});

**Comment by balinterdi** [comment]
That's actually good like this.

What happened is that I transformed the "old-style" action (for lack of a better name) where you just pass the name of an action as a property of the controller (which is a string and was passed into the `onClick` property of the component) to a "closure" action that gets passed as a simple function and thus need to be be called as such.

The `sendAction` is a special form for calling old-style actions and under the hood looks up the action with that name and fires it. With closure actions, no special treatment is necessary, you just "get" it and call it.

Does that make sense?
