### ISSUE TITLE
Typo on page 208 (backstage)

### ISSUE THREAD

**Issue by pcambra** [balinterdi/rarwe-issues#227]
'model.@each.isComlpeted', should be 'model.@each.isCompleted',

**Comment by pcambra** [comment]
hehe, nvm

**Comment by balinterdi** [comment]
I think this is the 3rd time an issue on this has been opened, quite understandably so ;)

**Comment by pcambra** [comment]
Sorry about that!
Having a great time following the examples, I'll wait a page or two next time :)

**Comment by balinterdi** [comment]
No, I did mean to scold you, I just wanted to point out that this is a common source of "early issue creation" but I totally get the reason for it :)
