### ISSUE TITLE
Can not delete/modify bands or songs

### ISSUE THREAD

**Issue by zzr994** [balinterdi/rarwe-issues#229]
After adding bands or songs, we can not modify or delete.
It will be nice to see how these features work, especially with the interaction with the back-end.
In the end we will have a complete CRUD implementation.

Thanks.

**Comment by balinterdi** [comment]
That's indeed something that would be a natural extension to the app.

I try to hold off from adding to this book as it already spans >300 pages which I think is a quite a bit for an intro book. I also find that there aren't that many new concepts to explain on the example of updating & deleting bands/songs. The one thing would be managing modal dialogs ("Are you sure you want to delete this song?").

Do you have something else in mind?

**Comment by zzr994** [comment]
Not sure what you mean by "natural extension".

To me reading this book, it is very difficult to understand the store and how it syncs up with the backend.  The concept of promises makes it even harder to understand.  

If you throw in modify and delete,  it is not clear what happens in the store and the backend. Also in modify there is a concept of some data elements getting "dirty".  How this is handled in Ember is not clear at all.

I understand where you are coming from for not adding to the book.  I think it will make the book that much better.  It does not have to be very extensive.  Even a brief description will suffice.  You can even make it like an exercise to the reader.  The readers themselves can collaborate on this forum to discuss issues and how to resolve them.

BTW, your article on the "Ember Building Blocks" was great to understand the big picture.

**Comment by balinterdi** [comment]
Good points, I see why you would like to see it in the book. I also agree that it could shed light on a few questions, though I'm not sure what you mean by "it is not clear what happens in the store at the backend". I think you mean the Ember Data store, the one in the front-end, right?

**Comment by zzr994** [comment]
Yes, that is correct.  I meant Ember Data store which is on the front-end.
