### ISSUE TITLE
Explicitly explain the need to set up the queryParams object for "sort" (Ch. 12)

### ISSUE THREAD

**Issue by medemas** [balinterdi/rarwe-issues#23]
At the beginning of Chapter 12 (Sorting and searching with query parameters), Ember's approach to QPs is explained, settling on the example:

```javascript

export default Ember.Controller.extend({
    …
    queryParams: {
        search: 's'
    },
    search: ''
    …
}) 

```

However, after writing the initial sorting tests and getting everything to pass except for the currentURL() assertion, readers are left to figure out that they have not yet necessarily included:

```javascript

export default Ember.Controller.extend({
    …
    queryParams: {
        sortBy: 'sort'
    },
    …
}) 

```

Which gets that last test passing. Was the lack of guidance intended as a learning challenge? I would suggest to at least state, after the initial 'search' example, that the reader must remember this to make one of the upcoming tests pass.

I should also mention that I realize this is resolved after implementing the search functionality in the next section. But it would save the reader confusion/worry if this was either mentioned ahead of time, or handled separately (as suggested above).

**Comment by balinterdi** [comment]
Great point, Mason, I clarified this and will release a book update today (including a couple of other things). Thank you!
