### ISSUE TITLE
npm install does not remove node modules

### ISSUE THREAD

**Issue by terryroe** [balinterdi/rarwe-issues#233]
In Chapter 3 (Version 2.10.0) it says to remove ember-welcome-page from package.json and run `npm install`.  This does not remove the node module.  Instead, you should just run `npm uninstall ember-welcome-page --save-dev` which will remove it from package.json and uninstall the node module.[](url)

**Comment by balinterdi** [comment]
Indeed, thank you.

Interesting that ember-welcome-page itself tells to modify package.json manually:

> To remove this welcome message, remove the ember-welcome-page add-on from your package.json file

**Comment by terryroe** [comment]
Yes, I guess they figure you "know" to do a nombom, or something similar, after you remove it.

**Comment by balinterdi** [comment]
Possible, but that is a far more complex way to remove a package.

Anyways, thank you again for simplifying this piece of the book.
