### ISSUE TITLE
Problems while trying to refactor stubs for testing

### ISSUE THREAD

**Issue by grandfatha** [balinterdi/rarwe-issues#234]
I tried adjusting the tests to use the Pretender stubs. The code is exactly like shown within chapter "Refactoring stubs".

When executing the tests I get the following error:

![error](https://cloud.githubusercontent.com/assets/404486/21646669/53ef36e8-d297-11e6-9b25-c9be2ffa1bf2.png)

I am confused and cannot continue. Can you please point me in a direction that explains what is going wrong?

**Comment by Brandon-Wolff** [comment]
I am having the same issue. I can replace parts of my test code with the stubSongs and stubBands functions just fine, but both stubCreateSong and stubCreateBand cause this to happen.

**Comment by Brandon-Wolff** [comment]
I've found the problem.  In the http-stubs.js file on page 189 of the book, there is a line in both the stubCreateBand and stubCreateSong functions:
`var response = [ responseItemForBand(JSON.parse(request.requestBody), newId) ];`
`var response = [ responseItemForSong(JSON.parse(request.requestBody), newId) ];`

Removing the square brackets from each of these worked for me.

`var response = responseItemForBand(JSON.parse(request.requestBody), newId);`
`var response = responseItemForSong(JSON.parse(request.requestBody), newId);`

**Comment by balinterdi** [comment]
Yes, I commented on the fix in the other issue, but in case you don't have access to that repository, the fix I came up with is:

```js
// tests/helpers/http-stubs.js
function responseItemForBand(data, id) {
  let bandId = id || data.id;
  return {
    id: bandId,
    type: 'bands',
    attributes: data.attributes,
    relationships: {
      songs: {
        links: {
          related: songsUrlForBand(bandId) // <= change: bandId instead of band.id
        }
      }
    }
  };
}
(...)
export default {
  (...)
 stubCreateBand: function(pretender, newId) {
    pretender.post('/bands', function(request) {
      let response = responseItemForBand(JSON.parse(request.requestBody).data, newId);
      return [200, {'Content-Type': 'application/vnd.api+json'}, JSON.stringify({ data: response }) ];
    });
  },

  stubCreateSong: function(pretender, newId) {
    pretender.post('/songs', function(request) {
      let response = responseItemForSong(JSON.parse(request.requestBody).data, newId);
      return [200, {'Content-Type': 'application/vnd.api+json'}, JSON.stringify({ data: response }) ];
    });
  },
}
```

I think removing the brackets had been done before that, but it's definitely needed, too.
