### ISSUE TITLE
Save 'band' when a new song is saved

### ISSUE THREAD

**Issue by portugaleren** [balinterdi/rarwe-issues#236]
I noticed that when I started to use a backend server (Firebase), songs were not shown with the band when the app was refreshed. That was because the reference to the song was not saved with the band. A band.save() cured that in routes/bands/band/songs.

      song.save().then(function() {
        controller.set('title', '');
        band.save();
      });

**Comment by balinterdi** [comment]
Right, Firebase is not a relational database engine and so you'll need to manage relationships yourself (or use a library, I guess).

Can the issue you describe be reproduced at any stage (either before hooking up the app to a real backend or after it) in the RARWE app?

**Comment by portugaleren** [comment]
You need to use Firebase as a backend. If you comment out the band.save(); then create a new band and songs you will still see the songs that belong to the band until you refresh the browser because then the relationships disappear from the store. If you examine the database you will see that there are no relations in 'band' to the 'songs'.

**Comment by balinterdi** [comment]
> You need to use Firebase as a backend.

Could you elaborate on this? I don't use Firebase anywhere in the book/app and the app should still work, at all stages.

**Comment by portugaleren** [comment]
I followed your book with internally defined data until chapter 10 Talking to a backend where I started to use Firebase as a backend instead of the one you use and that is when I noticed the missing relations in the 'band' table to the 'songs' table
