### ISSUE TITLE
updateRating action on p279 seems to have the wrong parameters

### ISSUE THREAD

**Issue by pcambra** [balinterdi/rarwe-issues#239]
I think when this is invoked 

```
<a href="#" {{action "updateRating" star star.rating}}
class="star-rating glyphicon {{if star.full
'glyphicon-star' 'glyphicon-star-empty'}}">
```
It should be this instead
```
<a href="#" {{action "updateRating" song star.rating}}
class="star-rating glyphicon {{if star.full
'glyphicon-star' 'glyphicon-star-empty'}}">
```

As the updateRating method expects a song parameter.

**Comment by balinterdi** [comment]
To my eyes, the two snippets are identical. What am I missing?

**Comment by pcambra** [comment]
Haha, yeah, it took me a while too :/

Instead of ```action "updateRating" star star.rating``` I think it should be ```action "updateRating" song star.rating```

s/star/song

**Comment by balinterdi** [comment]
Thank you, Pedro, for doing my work in my stead :) Fixed.
