### ISSUE TITLE
Chapter 5 typos

### ISSUE THREAD

**Issue by asizer** [balinterdi/rarwe-issues#240]
In the e-book, v.20170217:

book p. 66, pdf p. 73
> We also want to show the songs of a band on the right when that **bands** is clicked.

should be

> We also want to show the songs of a band on the right when that **band** is clicked.

book p. 68, pdf p. 75
> Consequently, the bands.band template **could can** be deleted, and the app would continue working just as before.

should be

> Consequently, the bands.band template **could** be deleted, and the app would continue working just as before.

**Comment by balinterdi** [comment]
@asizer Thank you very much, I just fixed both of them.
