### ISSUE TITLE
Chapter 2 - npm install -g ember-cli version needs updating to match

### ISSUE THREAD

**Issue by mikej** [balinterdi/rarwe-issues#242]
In this paragraph:

> Make sure you have the latest Ember CLI, so that the ember command we'll use throughout the book generates the right things and works the same way on your machine as in the book. The `npm install -g ember-cli@2.10.0` step above should have taken care of this

The `ember-cli` version needs updating to match the `$ npm install -g ember-cli@2.12.1` command in the instructions higher up.

**Comment by balinterdi** [comment]
@mikej I think you're reading an older version (which probably contains the "bug" you describe). The latest book version is updated to Ember 2.13 and the paragraph above reads as:

> Make sure you have the latest Ember CLI, so that the `ember` command we'll use
throughout the book generates the right things and works the same way on your
machine as in the book. The `npm install -g ember-cli@2.13.1` step above should
have taken care of this but if you already had it installed and skipped that
step, you should double check with `ember -v`.

The book version is both in the filename and in the Preface. It should read:

> (You are reading version 20170524 of this book.)

**Comment by mikej** [comment]
Thanks @balinterdi - I've just downloaded the updated version now.

I also followed you on Gumroad, I'm not sure if that sends email notifications of updates, or only for completely new products that you release, but will find out 🙂
