### ISSUE TITLE
Issue with displaying songs in Chapter 10

### ISSUE THREAD

**Issue by maxx1128** [balinterdi/rarwe-issues#244]
In chapter 10, when connecting the app to Ember Data, `{{ song.name }}` star rating component returns a promise object instead of the name itself. It was fixed for me by changing it to `{{ song.band.name }}`, likely due to the different way it referenced the info.

**Comment by balinterdi** [comment]
Sorry for the delay about getting back on this.

Could you specify which page is this on? I searched Chapter 10 but didn't find the `{{song.name}}` you refer to.
