### ISSUE TITLE
Diff Markers on Page 8

### ISSUE THREAD

**Issue by terryroe** [balinterdi/rarwe-issues#254]
In Git, the line that was deleted usually precedes the line that was added.

It might also be helpful to highlight the entire line with a background color (red for deletion, green for addition) like Github does in their diff tool.

**Comment by balinterdi** [comment]
> In Git, the line that was deleted usually precedes the line that was added.

That's how it should be in the book, too. I spot checked a few instances and found them in order. Could you specify where it's not so?

I added adding color to the backgrounds as a todo, great suggestion.

**Comment by terryroe** [comment]
I think it was just the one instance on page 8 (see issue title).

**Comment by balinterdi** [comment]
Ah, I was too distracted it seems.

I released book version 2.18 about an hour ago but the fix will make it into the next one.
