### ISSUE TITLE
Appendix Link on Page 11

### ISSUE THREAD

**Issue by terryroe** [balinterdi/rarwe-issues#255]
On page 11 of the PDF, there is a "link" to the Appendix in red, but it does not link to anything.  It would be nice if it linked to the Yarn item in the Appendix.

Also, the appendix is referred to as Encore earlier in the book, so maybe that term should be used here instead of, or in addition to, Appendix.

**Comment by balinterdi** [comment]
Nice catch, thank you. There was a bug in the script that builds the book that caused the link to be corrupt, which I've now eliminated (not the script, the bug :) ),
