### ISSUE TITLE
Missing import in chapter 9

### ISSUE THREAD

**Issue by jfelipe** [balinterdi/rarwe-issues#261]
`import { isEmpty } from "@ember/utils";` is missing on Chapter 9, page 120 when adding the afterModel code to check if there is a description for a band.

**Comment by balinterdi** [comment]
Thank you, Juan, that's fixed now.

**Comment by TheRealKevinM** [comment]
I do not see this code snippet `import { isEmpty } from "@ember/utils"; ` as of yet in the emberjs-2 book. I was able to resolve it by using Ember.isEmpty in the function instead but neither are mentioned so it took some sleuthing.
