### ISSUE TITLE
Chapter 6 - Adding Bands & Songs Issues

### ISSUE THREAD

**Issue by michael-harrison** [balinterdi/rarwe-issues#262]
While running through chapter 6 I started doing some manual testing so I could get a feel on how the actions where being triggered.  Following are some of the tests done along with issues:

**PASS: Add a new band**
_steps_
1. Refresh the page (if needed)
1. Enter in the new band name in the 'New band' field
1. Click on the associated button
1. Note the new band is now in the list

**PASS: Add a band when another band is selected**
_steps_
1. Select a band in the list of bands
1. Enter in the new band name in the 'New band' field
1. Click on the associated button
1. Note the new band is now in the list

**FAIL: Add a song for a new band**
_steps_
1. Refresh the page (if needed)
1. Enter in the new band name in the 'New band' field
1. Click on the associated button
1. Note the new band is now in the list
1. Select the new band
1. Enter in a new song name in the 'New song' filed
1. Click on the associated button
1. Note the song is not added
1. Note the error in the console
```
Nothing handled the action 'createSong'. If you did handle the action, this error can be caused by returning true from an action handler in a controller, causing the action to bubble.
```

**FAIL: Add a song for an existing band**
_steps_
1. Refresh the page (if needed)
1. Select the band
1. Enter in a new song name in the 'New song' filed
1. Click on the associated button
1. Note the song is not added
1. Note the error in the console  
```
Nothing handled the action 'createSong'. If you did handle the action, this error can be caused by returning true from an action handler in a controller, causing the action to bubble.
```

**Song Addition Fix**
_**DISCLAIMER: Some the terminology may not be totally correct because I wrote this before progressing past chaper 6**_

On closer inspection it would seem the `createSong` action was getting handled on the `app/routes/bands.js` controller rather than the `app/routes/bands/band/songs.js` controller.  I'm assuming this is because we're currently viewing the selected band.

 To fix the issue I moved the creation code from `app/routes/bands/band/songs.js` to `app/routes/bands.js` with one minor modification.  Because the `createSong` was being handled on the bands controller we'd get back bands controller when calling `this.get('controller')`.  We need the songs controller so I modified the  first line of the function to  `this.controllerFor('bands.band.songs')`.

```javascript
import Route from '@ember/routing/route';
import Band from 'rarwe/models/band';
import Song from 'rarwe/models/song';

export default Route.extend({
  model: function () {...},

  actions: {
    createBand: function () {
      let name = this.get('controller').get('name');
      let band = Band.create({name: name});
      this.modelFor('bands').pushObject(band);
      this.get('controller').set('name', '');
    },
    createSong: function () {
      let controller = this.controllerFor('bands.band.songs');
      let band = this.modelFor('bands.band');
      let title = controller.get('title');
      let song = Song.create({title: title, band: band});
      band.get('songs').pushObject(song);
      controller.set('title', '');
    }
  }
});
```

While this works I'm happy to be told its wrong so guidance either way would be welcomed.
P.S. I've create a repo and throughout the tutorial I've been doing commits.  It may give some indication as to why I'm having this problem:  https://github.com/michael-harrison/rarwe

**Comment by michael-harrison** [comment]
I found the issue and it was the location of the songs.js route.  It should have been in `app/routes/bands/band/songs.js` rather than `app/routes/bands/songs.js`.  Newbie oversight.

**Comment by balinterdi** [comment]
Hey Michael,

Glad you found it (and that the book doesn't have that bug :) ).
