### ISSUE TITLE
There are no songs yet. Why don't you create one? is displayed after page refresh

### ISSUE THREAD

**Issue by belgoros** [balinterdi/rarwe-issues#264]
I followed the excellent book and discovered a weird behaviour after implementing the steps described in **chapter 8**.
Here is hw to reproduce it:
- create a new band

<img width="1173" alt="band_created" src="https://user-images.githubusercontent.com/83579/36037569-7005752e-0dbd-11e8-8d49-c17916df9271.png">

- do not click on **create one?** link.
- refresh the current page (hit `F5`or `CMD-R` or whatever exists on your OS);
- the newly created band is gone from the list, but l'URL is not changed and the message inviting to create a new song is still displayed.

<img width="1203" alt="page_refreshed" src="https://user-images.githubusercontent.com/83579/36037710-dc303ad6-0dbd-11e8-9d85-e2a477019ca1.png">
- if you nevertheless try to create a new song, you'll get an error in your browser console:

```
songs.js:18 Uncaught TypeError: Cannot read property 'get' of undefined
    at Class.createSong (songs.js:18)
    at Router$1.triggerEvent (router.js:1023)
    at trigger (router.js:111)
    at Router$1.trigger (router.js:1699)
    at Class.send (router.js:325)
    at Class.send (action_handler.js:41)
    at action.js:141
    at exports.flaggedInstrument (ember-metal.js:3787)
    at action.js:140
    at Backburner.run (backburner.js:537)

```

**Comment by balinterdi** [comment]
Hey Serguei, that's actually a consequence of only having the records in memory. A new band (Scorpions, in your case), will have its own page and URL but once you refresh the app, it's gone and only those in the code are recreated (the 3 ones you see on the 2nd screenshot).

If you actually want to do something with that no-longer-existing band, you'll get the error you see.

Does that make sense?

**Comment by belgoros** [comment]
Yes, sure ! I got it, thanks a lot, Balint
