### ISSUE TITLE
p29 - Missing diff to remove 'A' array

### ISSUE THREAD

**Issue by stuartluscombe** [balinterdi/rarwe-issues#266]
Prior to adding the 'Song' object on page 29 there is an import statement of:

`import { A } from '@ember/array';`

And a subsequent return:

`return A([blackDog, yellowLedbetter, pretender]);`

This is not in the code listing for p29, which is fine as it is being replaced, but the listing does not state that it should be removed.

**Comment by balinterdi** [comment]
Thank you for spotting this, Stuart.

The import and calling `A(...)` in the return should actually still be there, so it shouldn't be removed. 

This doesn't break the app as current Ember extend the Array prototype but the framework is moving away from this practice and so it should explicitly be wrapped in `A`.

I've fixed this now.
