### ISSUE TITLE
[cccliii]extractError(e) missing import

### ISSUE THREAD

**Issue by belgoros** [balinterdi/rarwe-issues#268]
In Appendix, **async functions** section, there is a catch block defined as follows in `saveBand` action:
```
...
catch(e) {
    this.get('errorTracker').send(e);
    this.set('errorMessage', extractError(e));
  }
```
It fails `error  'extractError' is not defined  no-undef` when starting the app.
I'm using `20180302` version of the book.

**Comment by balinterdi** [comment]
Good point. The general rule is that if there's no comment in the code snippet that shows which file it is, it's not part of the application and thus it doesn't need to run. This is explained in the Introduction:

> There are some code snippets in the book that only serve demonstrational
purposes and are not part of the application. They can be discerned by not
having a comment header that designates the file to modify.

That said, you're right that in this case, as I use the `saveBand` action as example which *is* part of the app, I should make things clearer, so I added this:

Note that the exact details of the `errorTracker` service and the `extractError` function are not important in this context; the point is to show how async functions provide a clearer way of writing code.

**Comment by belgoros** [comment]
Great, thank you.

**Comment by balinterdi** [comment]
No problem!
