### ISSUE TITLE
Using ES2017’s async and await

### ISSUE THREAD

**Issue by belgoros** [balinterdi/rarwe-issues#269]
It seems like we should enable Babel’s polyfill in  `ember-cli-build.js`:
```
let app = new EmberApp(defaults, {
    // Add options here
    babel: {
      includePolyfill: true
    },
  });
```
When starting the app, you will still get a deprecation warning:
```
DEPRECATION: Putting the "includePolyfill" option in "babel" is deprecated, please put it in "ember-cli-babel" instead.
```
I didn't find any lines about that in Ember 3 version book. Any ideas ?

**Comment by balinterdi** [comment]
[`ember-maybe-import-regenerator`](https://github.com/machty/ember-maybe-import-regenerator) should take care of that. It also results in a smaller payload than the Babel polyfill.

It's a default devDep for new Ember projects and it listed as such in the Ember CLI chapter.

Are you getting an error message that leads you to think that the polyfill is missing?

**Comment by belgoros** [comment]
Ah, my bad. I've just updated the dependencies from the previous book version to use Ember `3.0.0` and, of course the above add-on didn't exist in `package.json`. I had to install it manually as `ember install ember-maybe-import-regenerator`. Thank you.
