### ISSUE TITLE
Chapter 6 - Typos

### ISSUE THREAD

**Issue by j-brennan** [balinterdi/rarwe-issues#272]
Just grouping a few minor typos together from Chapter 6:

File version: `Rock and Roll with Ember.js 3 (20180302).pdf`

- [x] p73
The **others** blocks should be added
The **other** blocks should be added

- [x] p82
Two **actions** calls, saveBand and cancelAddBand, were also added
Two **action** calls, saveBand and cancelAddBand, were also added

- [x] p99
Finally, we **inititate** a **transaction** to the songs page
Finally, we **initiate** a **transition** to the songs page

- [x] p101
but it would **even be** nicer to
but it would **be even** nicer to
(might just be the way I say it!)

**Comment by balinterdi** [comment]
Thanks, I must have been tired when I wrote these (not that I don't make errors when I'm fresh, but `others blocks` and `actions calls`??).
