### ISSUE TITLE
Chapter 7 - Dumbing down cleanup

### ISSUE THREAD

**Issue by j-brennan** [balinterdi/rarwe-issues#273]
File version: `Rock and Roll with Ember.js 3 (20180302).pdf`

On page 113, in the section titled `Dumbing down the component`, you talk about how the `item` property isn't really required by the component.

The template snippet on page 113 shows how you pass `song` to the `updateRating` action instead. Couldn't the `item=song` attribute also be removed from the `star-rating` component call too?

`{{star-rating class="fr" rating=song.rating item=song onClick=(action 'updateRating' song)}}`

becomes

`{{star-rating class="fr" rating=song.rating onClick=(action 'updateRating' song)}}`

Also a very minor typo in `The roadie says` section at the end:

we'll set up a decent rendering test for in the Testing chapter
we'll set up a decent rendering test **(for it)** in the Testing chapter

**Comment by balinterdi** [comment]
Very nice catch, James, passing `item=song` is indeed no longer necessary, that was the whole point. I fixed it and the small typo, too.
