### ISSUE TITLE
p125 - Incorrect CSS class in ul

### ISSUE THREAD

**Issue by stuartluscombe** [balinterdi/rarwe-issues#275]
On p125 the ul reads as:

`<ul class="nav">`

However this means the list style will default to using the 'disc' style. I corrected by changing it to.

`<ul class="rr-nav">`

**Comment by samrose** [comment]
Confirmed here too

**Comment by samrose** [comment]
confirmed on 

``` javascript
<!-- app/templates/bands/band.hbs -->
<nav class="rr-navbar" role="navigation">
  <ul class="nav">
    <li class="rr-navbar-item">{{link-to "Details" "bands.band.details"}}</li>
    <li class="rr-navbar-item">{{link-to "Songs"   "bands.band.songs"}}</li>
  </ul>
</nav>
{{outlet}
```
Excerpt From: Balint Erdi. “Rock and Roll with Ember.js 3 (version: 20180302).”

**Comment by balinterdi** [comment]
Thank you, Stuart.

One of the last-minute changes was to consistently use the `rr` prefix for CSS classes and I missed a few instances (see also #276). Fixed now.
