### ISSUE TITLE
p92 Invalid end tag `hr` 

### ISSUE THREAD

**Issue by a89529294** [balinterdi/rarwe-issues#278]
In Chapter Templates and data bindings, for the file application.hbs
I had to remove the closing hr tag otherwise I get 
Invalid end tag `hr` (on line 5) (void elements cannot have end tags).

**Comment by balinterdi** [comment]
Hi Albert,

I don't see a `<hr>` tag anywhere in the book or in the code and definitely not on page 92:
https://cl.ly/1y0L463n3Q2P

What am I missing?
