### ISSUE TITLE
pages 162 and 165 Rock and Roll with Ember.js 3 (version: 20180302)

### ISSUE THREAD

**Issue by samrose** [balinterdi/rarwe-issues#279]
On page 162 an example is shown for populating the app/models/band.js file

``` javascript
import EmberObject, { computed } from '@ember/object';
import { dasherize } from '@ember/string';

export default EmberObject.extend({
  name: '',

  slug: computed('name', function() {
    return dasherize(this.get('name'));
  })
});
```

However, on subsequent page 165, the line 

``` javascript
return dasherize(this.get('name'));
```

appears to change into 

``` javascript
return this.get('name').dasherize();
```

Was this intended?

**Comment by balinterdi** [comment]
Thank you, Sam, great catch.

No, it's not intended, I don't want to use any prototype extensions (e.g `this.get('name').dasherize`) so `dasherize(this.get('name'))` is the right way.
