### ISSUE TITLE
RARWE 3 (20180302) - Chapter 8: Advanced routing | 126

### ISSUE THREAD

**Issue by sergiolepore** [balinterdi/rarwe-issues#280]
There's a code snippet there that adds `description` to the "Pearl Jam" model. That code snippet has two inconsistencies:

1. Minor: models were previously declared in a single line (Chapter 5, page 59), but now they are multi-line
2. This one is weird :yum: All `songs` were created using `A([song1, song2, ...])` but now, for the `fooFighters` model, there's a `makeArray(pretender)` that I couldn't find anywhere.

**Comment by balinterdi** [comment]
Thank you, Sergio, good catch.

I wanted to get rid of `makeArray`s everywhere, but missed this one. It should just be:

```js
    let fooFighters = Band.create({
      name: 'Foo Fighters',
      songs: A([pretender])
    });
```

Fixed and will go out in the next release.
