### ISSUE TITLE
page 171 Mirage server does not get automatically bound in acceptance tests

### ISSUE THREAD

**Issue by MakMcFly** [balinterdi/rarwe-issues#288]
Adding
```
ENV['ember-cli-mirage'] = {
  enabled: true,
  autostart: true
};
```

to the test block environment in `environment.js` fixed this. Relevant issue: https://github.com/samselikoff/ember-cli-mirage/issues/1279

**Comment by balinterdi** [comment]
I've fixed this in another (more stable, I think) way, by adding the `setupMirageTest` in all acceptance tests. See [here](https://github.com/samselikoff/ember-cli-mirage/issues/1279) for more info.
