### ISSUE TITLE
Version 20180302, Chapter 8, Pg 131: Possible revision necessary

### ISSUE THREAD

**Issue by cclinard84** [balinterdi/rarwe-issues#289]
After generating the bands/band/details route the sentence reads:

> Make sure that the route was not added to a separate block, like this has been: 

The code block following this sentence is actually correct so my suggestion would be to remove the sentence. Modification of the sentence after the code block would then be necessary and my suggestion would be:

> If `this.route('details')` is not under the already existing `band` route, simply move it as shown above.

**Comment by balinterdi** [comment]
Great catch, thank you!
