### ISSUE TITLE
Version 20180302, Chapter 10, Pg 187: Missing quotation mark in a code snippet

### ISSUE THREAD

**Issue by cclinard84** [balinterdi/rarwe-issues#291]
Missing a closing quotation mark in the following code snippet.

![2018-03-22_10-51-14](https://user-images.githubusercontent.com/26779711/37777916-0b6f061c-2dbf-11e8-8983-48a8810d6f05.png)

**Comment by balinterdi** [comment]
Thank you, you have a sharp eye.
