### ISSUE TITLE
Version 20180302 Additions needed and grammar mistakes

### ISSUE THREAD

**Issue by MakMcFly** [balinterdi/rarwe-issues#293]
Page **159** Codeblock should be denoted as app/controllers/bands/band/songs.js instead of app/routes/bands/band/songs.js

Page **157** this.transitionToRoute('bands.band.songs', newBand.get('slug')); to this.transitionToRoute('bands.band.songs', newBand);

Page **173** Plus sign should be next to await visit('/');

Page **177** afterEach hook function not necessary? Server does not resolve the db object

Page **196** Plus sign next to Model | Band

Page **208** Add `import { computed } from '@ember/object';` to imports

Page **219** Add currentURL to import from `'@ember/test-helpers'` line

Page **257** Typo with `ember geneate route login` at the top of the page

**Comment by balinterdi** [comment]
Hi Michael, thank you for all of this. I've fixed all of them except for:

> Page 157 this.transitionToRoute('bands.band.songs', newBand.get('slug')); to this.transitionToRoute('bands.band.songs', newBand);

That's already `this.transitionToRoute('bands.band.songs', newBand);` in the book. Unless I misunderstand something.

> Page 177 afterEach hook function not necessary? Server does not resolve the db object

This whole block is not needed as Mirage fixed it on the day of my publishing the book. I'll fix it for the next version release.

**Comment by MakMcFly** [comment]
I didn't make that clear enough, that's my mistake.

It needs to have something denoting that it was changed, because it is changed on Page **157**, but can easily be glanced over as there's no marker for that change.

It was previously `this.transitionToRoute('bands.band.songs', newBand.get('slug'));` on Page **134**.

Thanks for the response, loving the book!

**Comment by balinterdi** [comment]
Nice catch, thank you.

The error is on Page 157, it should still be `newBand.get('slug')` as I advised against using Ember objects as the parameter for the `transitionToRoute` (see "Skipping model resolution" in the Advanced routing chapter).

Happy to hear you like the book :)
