### ISSUE TITLE
Version 20180302, Chapter 11, Pg 215: Necessary import for using computed

### ISSUE THREAD

**Issue by cclinard84** [balinterdi/rarwe-issues#294]
Since we are using a computed property in this code snippet wouldn't it be wise to import computed here?

![2018-03-22_13-39-06](https://user-images.githubusercontent.com/26779711/37787928-8db9019c-2dd6-11e8-8c8a-6ef8039f1830.png)

**Comment by balinterdi** [comment]
Thank you, Matt!
