### ISSUE TITLE
chapter 3 typos

### ISSUE THREAD

**Issue by jaimeiniesta** [balinterdi/rarwe-issues#30]
> We can now return the application template

Better "We can now return **to** the application template".

**Comment by jaimeiniesta** [comment]
> So kill the ember serve process and then launch it again.

Some readers may wonder how to kill a process. Maybe it would be better to add "by pressing Ctrl-C".

**Comment by balinterdi** [comment]
Thank you for this and the others, Jaime, great catches!

The only suggestion I did not end up "merging" is the one about specifying how to kill a process. I'd had a section on troubleshooting how to install node but I realized (somebody had me realize) that this would be too much to explain. People should have a basic knowledge about simple OS operations, or they should be able to Google for the solution (which, in this case, should not take more than a minute).
