### ISSUE TITLE
Non-matching screenshot in book (with the actual state of the app at that point)

### ISSUE THREAD

**Issue by headquarters** [balinterdi/rarwe-issues#300]
I'm on Chapter 3: Template and data bindings (page 24)(version 20180302)  and I've [added the styles suggested up to this point](https://github.com/headquarters/rock-and-roll-ember/blob/master/app/styles/app.css) (I took a shortcut and copied the styles from app.css in the private repo), but my templates are not picking up the styles. 

![screen shot 2018-04-08 at 9 42 46 am](https://user-images.githubusercontent.com/347079/38468246-36e77ff4-3b11-11e8-9cb0-84fc16b58220.png)

I don't see any requests for ANY CSS files. I don't think I missed any steps up to this point, so I'm really confused what wiring needs to be hooked up to make this work. 

The repo I have set up for following along with the book is here: https://github.com/headquarters/rock-and-roll-ember.

```
Michaels-MBP:rock-and-roll-ember$ ember -v
ember-cli: 3.0.2
node: 8.10.0
os: darwin x64
```

Let me know if you need any more information.

**Comment by headquarters** [comment]
Update: now styles are loaded after installing tachyons. So, to recreate you'd have to check out the repo at [this commit](https://github.com/headquarters/rock-and-roll-ember/commit/23cfd1f7b3e752f897379b2ba99dbbeeb8e462af), since it's working on the latest of master. :\

**Comment by balinterdi** [comment]
Hey Michael,

I tried to reproduce this (with the exact commit you gave), but styles are loaded correctly for me:
https://cl.ly/3l1a011f1s2L

I'm closing this, but feel free to reopen.

**Comment by headquarters** [comment]
You are right! I checked out that commit and I see my rock-and-roll-ember.css file being loaded in with its styles. Here's what confused me--in the book, on page 23, the list in the screenshot is shown in a sans-serif font (first screenshot below), but at this point in following along my app had the default serif font (second screenshot below). 

Book, page 23:
![screen shot 2018-04-19 at 8 02 33 pm](https://user-images.githubusercontent.com/347079/39024126-c49737aa-440c-11e8-8a4e-a6b8164659c6.png)

Code running from my commit:
![screen shot 2018-04-19 at 8 02 18 pm](https://user-images.githubusercontent.com/347079/39024131-c7a50346-440c-11e8-8216-fb3941d9cc2a.png)

My app UI matches what you have in your screenshot, though, so I didn't miss anything after all, I was just stumped by a small discrepancy between what I saw in the book and what I saw on screen. Thanks for checking.

**Comment by balinterdi** [comment]
> My app UI matches what you have in your screenshot, though, so I didn't miss anything after all, I was just stumped by a small discrepancy between what I saw in the book and what I saw on screen. 

I thought I understood until your last paragraph :) So does the screenshot in the book match how the app is rendered at that point? If not, I'll need to update the screenshot (or the book :) )

**Comment by headquarters** [comment]
I'll try to clarify that last thing: the UI of app from the commit I posted matches the screenshot you provided in your image (the cl.ly screenshot). However, neither of those match what it's in the book 100% because the book shows a sans-serif font, whereas what we're running shows a serif font, so something is not styled the same. I am running Chrome, if that makes any difference.

**Comment by balinterdi** [comment]
Gotcha, I'll then update the screenshot in the book. Thank you!

**Comment by balinterdi** [comment]
Fixed, ty!

**Comment by headquarters** [comment]
Thank you for fixing that and for editing the title for clarity.
