### ISSUE TITLE
Change file-marking headers for CSS code snippets

### ISSUE THREAD

**Issue by smackesey** [balinterdi/rarwe-issues#305]
Throughout the text, the file to be edited for a given code snippet is indicated with `// path/to/file` at the top of the snippet. This makes sense for JS files, but for CSS files a valid CSS comment (i.e. `/* comment */`) should be used instead. Not only will this correct highlighting (see, for instance, the snippet at the bottom of p165), but it also may spare people some issues -- I'm not that familiar with CSS and didn't realize `//` wasn't a valid comment. I copy-pasted one of these snippets directly and it caused weird errors until I realized my mistake.

**Comment by balinterdi** [comment]
Thank you, Sean, that's a very good point. I've fixed all CSS comments now.
