### ISSUE TITLE
Chapter 6 - Page 93 - Change 'song' to 'band'

### ISSUE THREAD

**Issue by jagthedrummer** [balinterdi/rarwe-issues#309]
In Chapter 6, on Page 93

> It would greatly improve the user experience of creating a new **song** if we could save the band just by hitting the return key instead of clicking the small Add button.

should be

> It would greatly improve the user experience of creating a new **band** if we could save the band just by hitting the return key instead of clicking the small Add button.

**Comment by balinterdi** [comment]
Thank you, Jeremy, this is fixed now.
