### ISSUE TITLE
Chapter 7 - An action named 'setRating' was not found

### ISSUE THREAD

**Issue by jagthedrummer** [balinterdi/rarwe-issues#310]
On page 106, the very first introduction of code to `app/templates/components/star-rating.hbs` contains a reference to the `setRathing` method which is not added to the component until page 111, but on page 110 you say that "we have a fully functioning component", which isn't true at that point. There are also a couple of side roads between 106 and 111, so I think you probably should remove the `onclick` handler from the first implementation of that template and introduce it along with the `setRating` method all as the single concept of "wiring and handling actions in a component".

**Comment by balinterdi** [comment]
Thank you, Jeremy, that's a great suggestion.

I restructured the explanation in that chapter.
