### ISSUE TITLE
Chapter 9 - missing `event` in `saveBand`

### ISSUE THREAD

**Issue by jagthedrummer** [balinterdi/rarwe-issues#313]
Related to #277, on page 157 the definition for `saveBand` should include the `event`.

```
async saveBand() {
```

should be

```
async saveBand(event) {
```

It's shown that way in the code sample of #277 but wasn't called out directly, so I'm not sure if you're already aware.

**Comment by balinterdi** [comment]
Yes, fixed there. Thank you!
