### ISSUE TITLE
Chapter 10 - Page 171 - Making the first test pass?

### ISSUE THREAD

**Issue by jagthedrummer** [balinterdi/rarwe-issues#315]
I've run `ember install ember-cli-mirage` and have added `this.get('/bands');` to `mirage/config.js` but the acceptance test is still failing.

```
Source: | Error: Ember Data Request GET /bands returned a 404 Payload (Empty Content-Type) Not found: /bands     at ErrorClass.EmberError (http://localhost:7357/assets/vendor.js:24529:25)     at ErrorClass.AdapterError (http://localhost:7357/assets/vendor.js:159130:15)     at new ErrorClass (http://localhost:7357/assets/vendor.js:159148:22)     at Class.handleResponse (http://localhost:7357/assets/vendor.js:171200:18)     at ajaxError (http://localhost:7357/assets/vendor.js:171693:25)     at Class.hash.error (http://localhost:7357/assets/vendor.js:171281:23)     at fire (http://localhost:7357/assets/vendor.js:3609:31)     at Object.fireWith [as rejectWith] (http://localhost:7357/assets/vendor.js:3739:7)     at done (http://localhost:7357/assets/vendor.js:9648:14)     at XMLHttpRequest.<anonymous> (http://localhost:7357/assets/vendor.js:9889:9)
```

In the dev tools I can see a request going to `http://localhost:7357/bands` which seem to be trying to hit the test runner.

Is there something else I have to do to get mirage working?

A related quibble: On page 171 the code sample shows adding two lines:

```
+ this.get('/bands');
+ this.get('/bands/:id');
```

But the text immediately following the sample indicates that only a single line was added.

> This sole line makes the test pass...

**Comment by balinterdi** [comment]
Hey Jeremy,

That was indeed an error. Two lines are not a single line :) and you needed an extra `setupMirageTest` call to make the test pass. Here is what the update section looks like in the book now:

    These two lines will mock out the http requests the app makes against the backend. Since we use Mirage for this, we also need to set up our test to work with it:

    ```js
    // tests/acceptance/bands-test.js
    import { module, test } from 'qunit';
    import { visit, currentURL } from '@ember/test-helpers';
    import { setupApplicationTest } from 'ember-qunit';
    + import setupMirageTest from 'ember-cli-mirage/test-support/setup-mirage';

    module('Acceptance | bands', function(hooks) {
      setupApplicationTest(hooks);
    +  setupMirageTest(hooks);

      (...)
    });
    ```

    `setupMirageTest` should come after the appropriate setup method for the test
    (in this case, `setupApplicationTest`). It also gives us access to the main
    entry point of Mirage, `this.server`.

As noted, this should go out tomorrow with the 3.1 release.

I've also gone through the whole Testing chapter again, so it should be fine.
