### ISSUE TITLE
Chapter 13 - Query Params is missing from .mobi

### ISSUE THREAD

**Issue by jagthedrummer** [balinterdi/rarwe-issues#316]
In the .mobi version "Chapter 13 - Query Params" is listed in the TOC, but is not linked to anything. The text itself goes from the end of Chapter 12 directly to the beginning of Chapter 14.

**Comment by jagthedrummer** [comment]
I guess technically it's Chapter 11 (in the PDF, anyway). My mobi reader shows the Preface and intro sections as chapters.

Btw, 🤘 for including Them Crooked Vultures.

**Comment by balinterdi** [comment]
Oops, indeed, thank you very much for reporting this.

I need to take a deeper look, not sure what went wrong, it had worked before™

In the meantime, here is a killer song from TCV (too bad they only have a single album):

https://www.youtube.com/watch?v=Pz8EjuOx1C0

**Comment by balinterdi** [comment]
This is fixed now and the next release (3.2, slated for next week) will contain the fixed version. Let me know if you need it before that.
