### ISSUE TITLE
Version 20180504 - chapter-7: this.get('onClick')({...}) instead of this.onClick({})

### ISSUE THREAD

**Issue by belgoros** [balinterdi/rarwe-issues#317]
After modifying the action `setRating` on page `113` by adding the following snippet:
```
#components/star-rating.js
actions:{
  setRating(newRating) {
...
    return this.onClick({
        item: this.item,
        rating: newRating
      });
...
```
on page `114` the text references it as follows:

> this.get('onClick')({...}) calls the action passed in to the component (updateRating in the above case) with some optional parameters.

Wouldn't it be wiser to use the same, `this.onClick({...})` instead of `this.get('onClick')({...})` ?

Book edition: `rock-and-roll-with-emberjs-3-20180504`

Thank you.

**Comment by balinterdi** [comment]
Thank you, fixed!
