### ISSUE TITLE
Version 20180504 - chapter 10, page 191: wrong line reference

### ISSUE THREAD

**Issue by belgoros** [balinterdi/rarwe-issues#320]
The line number that you send to is not correct:
> Note that those properties can then be used in the inline template passed to `render` on line 19.

But the the above `render` helper is on line 20 of the corresponding code snippet
<img width="1029" alt="screen shot 2018-05-15 at 14 55 23" src="https://user-images.githubusercontent.com/83579/40057969-0d473a2a-5850-11e8-9421-a66fcb6d8d6e.png">

**Comment by balinterdi** [comment]
I shy away from referring to line numbers in code snippets because they can "break" if, for example, a new line is added somewhere in between. However, I've found it useful to have it in a few places.

Thank you for spotting the error.
