### ISSUE TITLE
Version 20180504 - chapter 10, page 193: wrong line reference

### ISSUE THREAD

**Issue by belgoros** [balinterdi/rarwe-issues#321]
> The important bit is on line 9 where we just fetch the single controller instance from the container.

<img width="1107" alt="screen shot 2018-05-15 at 15 03 18" src="https://user-images.githubusercontent.com/83579/40058336-24cf84bc-5851-11e8-8c87-46b278d51656.png">

I thing the line to be referenced is **11**.

**Comment by balinterdi** [comment]
Thank you!
