### ISSUE TITLE
Version 20180504 - chapter 11, page 215, 218: missing 'fillIn' import

### ISSUE THREAD

**Issue by belgoros** [balinterdi/rarwe-issues#322]
When adding a new test scenario on page 215, there is no mention about adding `fillIn` import. Page 218 code snippet proves that:
<img width="1016" alt="screen shot 2018-05-16 at 10 04 57" src="https://user-images.githubusercontent.com/83579/40104443-aa00a662-58f0-11e8-9aa9-8aa9d4975532.png">

It is used on the following line of the scenario:
```
test('Search songs', async function(assert) {
...
  await fillIn('[data-test-rr=search-box]', 'no');
```

**Comment by balinterdi** [comment]
Great catch, thank you, Serguei!
