### ISSUE TITLE
Version 20180504 - chapter 3, page 21 - "{{outlet}}" is not explained

### ISSUE THREAD

**Issue by edsnowden** [balinterdi/rarwe-issues#326]
On page 21 (of version 20180504) you say

> Ember's templating engine is built on top of Handlebars. Anything enclosed in mustaches ({{ ... }}) is a
> dynamic expression. The first such expression is a helper, {{#each}}.

However, that's not strictly true - the first expression is {{outlet}}, and it's not explained until page 41.

**Comment by balinterdi** [comment]
Good catch, Ed! I added a sentence to tell that `{{outlet}}` will be explained in the Routing chapter
