### ISSUE TITLE
Version 20180504 - frontmatter page iv - who -> whom

### ISSUE THREAD

**Issue by edsnowden** [balinterdi/rarwe-issues#327]
Apologies for being a grammar nazi...
> A fellow developer who I was working on a pet project with found this annoying enough to quit.

Who should be whom here... better yet I'd say "with whom X" rather than  "whom X with".

**Comment by balinterdi** [comment]
No worries, I'm quite the grammar nazi myself and love both to make and to receive such corrections. Fixed.
