### ISSUE TITLE
Version 20180504 - chapter 4, page 38 - locationType, not location

### ISSUE THREAD

**Issue by edsnowden** [balinterdi/rarwe-issues#328]
> So auto is assigned to the router's location property

Actually it's assigned to locationType.

**Comment by balinterdi** [comment]
Technically, this is true because the `locationType` value in the config (`config/environment.js`) becomes the `location` of the router (`app/router.js`), but to make this clearer, I rewrote it as follows:

> So `auto` is set as `locationType` in the config which is then assigned to the router's `location` property.  (...)

Thank you.
