### ISSUE TITLE
Version 20180504 - Minor Typos

### ISSUE THREAD

**Issue by chanderhan** [balinterdi/rarwe-issues#329]
Chapter 10 | Page 186 (Page 193 of PDF)
    Line 4 should be a +, not a minus.
`+ 4 | import { visit } from '@ember/test-helpers';`
Chapter 10 | 196 (Page 203 of PDF)
    Line 36 is missing a '2'
`+ 36 | assert.notOk(stiltskin.get('isGreatBand'), 'A band with less than **2** good songs is not a great 'band');`
Chapter 11 | 215 (Page 222 of PDF)
    Need to import fillIn 
```
- x   | import { visit } from '@ember/test-helpers';
+x   | import { visit, fillIn } from '@ember/test-helpers';
```
Chapter 13 | 247 (Page 254 of PDF)
    Line 10 should sort by title-asc, not title-desc (Line 4 takes care of the desc test)
`10 | await click('[data-test-rr=sort-by-title-asc]');`

**Comment by balinterdi** [comment]
Hey Connor,

Thank you very much for those.

A couple of these had already been fixed but there were a few left that I still needed to fix which I've done now.
