### ISSUE TITLE
20180104 version - addon chapter, font awesome issue

### ISSUE THREAD

**Issue by mathieupoterie** [balinterdi/rarwe-issues#331]
Hi Balint,

Many thanks for your book, I am just diving into ember for my new job, and your book is an amazing reference, I am learning a lot, and as a junior, I truly appreciate your great pedagogic skills.

I just saw one tiny mistake on p.273 of the 20180104 version 👍 

`{{#each stars as |star|}}
          <a href="#" {{action "updateRating" song star.rating}}
             class="star-rating glyphicon {{if star.full 'fa-star' 'fa-star-o'}}">
          </a>
{{/each}}`

When we try to switch into font awesome, it's not working, you just forgot to replace the class 'glyphicon' by the class 'fa' ;).

I am starting on monday, and feel way more confident now that I read your book, so thanks again !

Mathieu

**Comment by balinterdi** [comment]
Salut Mathieu,

Thank you for your words, I love hearing that people find my book useful for learning Ember.js.

And also thank you for spotting the error, I've fixed it for the last version of the RaRwE 2 book, it should go out with the 3.2 version of the book (so soon).

ps. Incidentally, I spent my last university year in Nantes, with a grant, and thoroughly loved both the city and my year there (I saw on your profile that you live there) :)
