### ISSUE TITLE
Version 20180504 - chapter 9, page 158 - Code error

### ISSUE THREAD

**Issue by ckbrewer33** [balinterdi/rarwe-issues#333]
In the code differences show for updating `app/controllers/bands.js`, on line 20 the code is left as 
`this.transitionToRoute('bands.band.songs', newBand.slug);`, when it needs to be changed to `this.transitionToRoute('bands.band.songs', newBand.id);` to work.

Correct me if I'm wrong, or if I missed the change somewhere else in the chapter, but I didn't see it.  (Also new to ember so I'll defer to your knowledge) 👍

**Comment by balinterdi** [comment]
You're absolutely right, this is an error, that I've just fixed.

Thanks a bunch!
