### ISSUE TITLE
Chapter 5: The option '--type' is not registered with the generate command.

### ISSUE THREAD

**Issue by jaimeiniesta** [balinterdi/rarwe-issues#34]
```
➔ ember generate route band --type=resource --path=':slug'
version: 0.2.7
The option '--type' is not registered with the generate command. Run `ember generate --help` for a list of supported options.
installing
  create app/routes/band.js
  create app/templates/band.hbs
installing
  create tests/unit/routes/band-test.js
```

**Comment by balinterdi** [comment]
Ok, that means I have to stop using `this.resource` in the routes earlier than I'd thought. That means that all module (file) paths will have to change so it is definitely not a 3-minute change but I'd have had to do it anyway at one point. Thanks a lot for bringing it to my attention!

**Comment by balinterdi** [comment]
I have updated both the code and the code examples, route names, etc. in the book. This should soon go out as the 1.13 release.
