### ISSUE TITLE
rarwejs 3 20180801 chapter 14 app/adapters/application

### ISSUE THREAD

**Issue by dschlauderaff** [balinterdi/rarwe-issues#345]
On page 270 of chapter 14 there is a reference to an application adapter at /app/adapters/application.js. The code snippet on the next page has a (. . .), indicating there is more code than shown, but I can't find that file referenced anywhere else in the book, or a generator for it.

I cannot get sign-up to work with the `ember serve --proxy=https://auth-api.rockandrollwithemberjs.com` endpoint, though the book says the app should work by that point. Posts to /users returns a 400 error. All of my tests through ch 14 are green.

**Comment by balinterdi** [comment]
@dschlauderaff Sorry about that. Could you paste the details of the 400 error when you try to sign up? Or provide a screenshot? Thank you.

**Comment by dschlauderaff** [comment]
![screen shot 2018-09-26 at 3 12 51 pm](https://user-images.githubusercontent.com/26337932/46106678-06a15f80-c19f-11e8-8548-0f43dea3708e.png)
<img width="717" alt="screen shot 2018-09-26 at 3 12 07 pm" src="https://user-images.githubusercontent.com/26337932/46106680-06a15f80-c19f-11e8-86e5-b80f8d5f5a88.png">
<img width="725" alt="screen shot 2018-09-26 at 3 11 41 pm" src="https://user-images.githubusercontent.com/26337932/46106681-06a15f80-c19f-11e8-9aed-b71c50fad00a.png">
<img width="1292" alt="screen shot 2018-09-26 at 3 16 10 pm" src="https://user-images.githubusercontent.com/26337932/46106735-1faa1080-c19f-11e8-945e-cdc63edb0a7a.png">

Please let me know if you need anything else.

**Comment by balinterdi** [comment]
The adapter should be created and indeed the book doesn't tell you to, I'm going to fix that. The `(...)` shouldn't be there, there's no skipped code there (I'll fix that, too).

For the error, could you remove the `password` attribute form the `user` model and try again? It should solve it, I came across this before.

**Comment by dschlauderaff** [comment]
Removing the password from the user model gives me the following error:

<img width="1422" alt="screen shot 2018-09-26 at 3 41 16 pm" src="https://user-images.githubusercontent.com/26337932/46108034-ad3b2f80-c1a2-11e8-94b8-d6d19cc2e8aa.png">

**Comment by balinterdi** [comment]
Sorry, that was wrong (and I'm getting tired). You should restore the password attribute, I've fixed the back-end problem, you should now be able to sign up with a new user.

**Comment by dschlauderaff** [comment]
It works now. Thank you.
