### ISSUE TITLE
extractServerError - will work for the only error only

### ISSUE THREAD

**Issue by belgoros** [balinterdi/rarwe-issues#349]
The present implementation of `extractServerError` function will work if the back-end server returns one and the only field validation error. I case if you have multiple fields validated in the back-end, you will get an array of errors like that:
``` 
{"errors":[{"status":422,"title":"Title","source":{"pointer":"/data/attributes/title"},"detail":"can't be blank"},{"status":422,"title":"Body","source":{"pointer":"/data/attributes/body"},"detail":"can't be blank"},{"status":422,"title":"Tag_ids","source":{"pointer":"/data/attributes/tag_ids"},"detail":"can't be blank"}]}
```
The above `Post` model has presence validation on the below attributes:
- title
- body
- tag_ids

The `extractServerError` code:
```
import { capitalize } from '@ember/string';

const generalErrorMessage = "Something went wrong, sorry.";

export default function extractServerError(errors) {
  if (!errors) {
    return generalErrorMessage;
  }

  let [ errorObject ] = errors;
  let { title, detail, source } = errorObject;

  if (!source) {
    return generalErrorMessage;
  }

  let { pointer } = source;
  let attributePath = pointer.split('/');
  let errorAttribute = attributePath[attributePath.length - 1];

  return errorAttribute === 'base' ? detail : `${capitalize(errorAttribute)} ${title}`;
}
```
The `errors` variable will contain 3 errors got from the back-end. But assigning it to `errorObject` will take the first only (what is really weird).

**Comment by balinterdi** [comment]
Right, the current implementation is naive in that it only displays the first error but I wonder if that's such a big problem. I think it's defendable to the alternative of possibly displaying all the errors and thus overwhelming the user.

**Comment by balinterdi** [comment]
True, good point.

Here is what I thought adding:

```
Also note that we only take the first error message from `errors`. That's a simple and valid approach so as not to overwhelm the user with multiple error messages. If they fix the error and submit again, they'll see another one, so they can correct them one by one. Your approach to handling errors might differ and that's fine.
```

**Comment by belgoros** [comment]
Looks good 👍
