### ISSUE TITLE
Chapter 5: "we did not copy their container"

### ISSUE THREAD

**Issue by jaimeiniesta** [balinterdi/rarwe-issues#35]
> We again copied the songs from the songs route from the previous chapter and added a new one, the wonderful Daughter from Pearl Jam. **We did not copy their container, SongCollection since songs are no longer going to to be listed on their own but next to their band**.

But, on the `app/routes/band.js` snippet just above this paragraph, we can see the SongCollection there, lines 34 and 35:

```js
var songs = SongCollection.create();
songs.pushObjects([blackDog, yellowLedbetter, daughter, pretender]);
```

(also, a duplicated word: "going to to be listed".

**Comment by balinterdi** [comment]
Thank you, Jaime, this was also found a few days ago by another reader (#28) and it will be fixed in the next book release.
