### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by officeguy** [balinterdi/rarwe-issues#350]
'model.@each.isComlpeted'
assume should be:
'model.@each.isCompleted'

on page 98, of version 3-20180801.pdf
Section: backstage, 'Computed Property Macros'

no functional impact, as it's just to illustrate the example.

ps.. great book!

**Comment by balinterdi** [comment]
@officeguy That trips a lot of people up. The misspelling is actually intended as it shows the danger of making typos in dependent keys of computed properties.  A few sections below I explain that the typo was deliberate (iirc I phrase it as "See what I did there?").

Thank you, I love hearing people enjoy the book!

**Comment by officeguy** [comment]
ah, nice one. I should have read further :)

thanks
