### ISSUE TITLE
testem.js decycle max depth

### ISSUE THREAD

**Issue by officeguy** [balinterdi/rarwe-issues#354]
Hi,

I have an issue I have been unable to resolve.
Refs: 
doc version: emberjs-3-20180801
page: 212
ember-cli: 3.3.0
node: 10.10.0
os: darwin x64

Adding the code to use the ( schema, request) , doesn't allow the query of multiple items in order to assess the state of the last item. 
Symptom in the testing instance of chrome:
```
Element [data-test-rr=song-list-item]:last-child exists
Source: | at DOMAssertions.findTargetElement (http://localhost:7357/assets/test-support.js:8812:16)     at DOMAssertions.hasText (http://localhost:7357/assets/test-support.js:8527:26)     at Object.<anonymous> (http://localhost:7357/assets/tests.js:43:62)
```
I added  this.server.logging = true to band-test.js, which then showed this output in the developer console of the testing instance of chrome:
```
Mirage: [200] GET /bandsserver.js:28 
Mirage: [200] GET /bands/1 server.js:28 
Mirage: [200] GET /bands/1/songs server.js:28 
```
more info is in the command window where I am running ember test --server : 
```
Acceptance | bands: Sort songs in various ways
    ✘ Element [data-test-rr=song-list-item]:last-child exists
            at DOMAssertions.findTargetElement (http://localhost:7357/assets/test-support.js:8812:16)
            at DOMAssertions.hasText (http://localhost:7357/assets/test-support.js:8527:26)
            at Object.<anonymous> (http://localhost:7357/assets/tests.js:43:62)
{ request: null,
  response:
   { data:
      [ { type: 'bands',
          id: '1',
          attributes:
           { name:
              'Decycle max depth reached at 6. You may override the default by setting "client_decycle_depth" in your testem config.' },
          relationships:
           { songs:
              'Decycle max depth reached at 6. You may override the default by setting "client_decycle_depth" in your testem config.' } } ] },
  raw:
   { _eventListeners:
      { loadend: [ null ],
        abort: [ null ],
[Press ENTER to run tests; q to quit; p to pause]      
```

I've then tried adding this to /rarwe/testem.js
```
client_decycle_depth: 1000,
```

stopping and re running the tests, then seems to allow some more data to be returned in the command window, (but not in chrome dev console) and the symptom remains the same in the testing chrome window.
```
Acceptance | bands: Sort songs in various ways
    ✘ Element [data-test-rr=song-list-item]:last-child exists
            at DOMAssertions.findTargetElement (http://localhost:7357/assets/test-support.js:8812:16)
            at DOMAssertions.hasText (http://localhost:7357/assets/test-support.js:8527:26)
            at Object.<anonymous> (http://localhost:7357/assets/tests.js:43:62)
{ request: null,
  response:
   { data:
      [ { type: 'bands',
          id: '1',
          attributes: { name: 'Them Crooked Vultures' },
          relationships: { songs: { links: { related: '/bands/1/songs' } } } } ] },
  raw:
   { _eventListeners:
      { loadend: [ null ],
        abort: [ null ],
        load: [ null ],
        progress: [ null ],
        loadstart: [ null ] },
     readyState: 4,

```

advice please :)

**Comment by balinterdi** [comment]
Hey,

I'm sorry you have this problem.

I've built the application from the start of the Query params chapter when this test is added and I've found everything in order so I wonder where the difference between our apps is.

> Adding the code to use the ( schema, request) , doesn't allow the query of multiple items in order to assess the state of the last item.

I'm not sure I got this right. Do you first see the error you describe when a custom (=not shorthand) Mirage handler is written, on page 205 (I use the page numbers on the pages in the book). Or does it only crop up later, on page 210, when the "Changing the sorting criteria" test is written?

At any rate, I gave you code access so that you can check where your code might differ from mine. Just use "git checkout testing" to go to *the end* of the testing chapter and "git checkout query-params" to do the same for the Query params chapter.

I hope that helps, let me know if it doesn't.

**Comment by officeguy** [comment]
thanks, I'm working though the code to work out where I went wrong. I'll close this for now.

..Marty

**Comment by officeguy** [comment]
I've compared all files up to the end of the testing chapter, and worked out I was missing the songs route and songs template. weird, must have gone off track somewhere.  works fine now. :)
thanks for the access to the repo.
