### ISSUE TITLE
Wrong module

### ISSUE THREAD

**Issue by Willibaur** [balinterdi/rarwe-issues#360]
Hi,

I think there is an error on Version 3.X on page `102` within **Controllers** chapter, where if I use `import Band from 'rarwe/models/band';` I get a `load module` error 

![image](https://user-images.githubusercontent.com/12820932/48985596-fc4d0480-f100-11e8-98af-f4fe49d6cd75.png)

but if I use `import Band from '../models/band';` it does work fine.

Thanks

**Comment by balinterdi** [comment]
@Willibaur Hey William. Did you close the issue because it turned out to work fine?

**Comment by Willibaur** [comment]
Hi @balinterdi 
Yes, it was a complete mistake by my side, I tried to delete the issue to not causing confusion amongst other users but could not find the way so I just closed it, I think I should leave a comment before.

Thanks for this awesome book

**Comment by balinterdi** [comment]
No worries, I just wanted to make sure there's nothing wrong in that part of the book.

Thank you, glad you like it!
