### ISSUE TITLE
Version 20181123 - p82 truncated lines

### ISSUE THREAD

**Issue by edsnowden** [balinterdi/rarwe-issues#363]
Lines 10, 11 and 12 in the code snippet on page 82 appear to be truncated in the PDF version of the book. (There was another instance of this on an earlier page but I thought it might just be my e-ink reader truncating it; this time I checked the PDF on macOS.)

Page 93 has an example of a wrapped insertion (lines 8 & 9 - should probably both be line 8?), although the following unlabelled line is garbled.

Perhaps where you are deliberately eliding the end of the line (e.g. because the line is one that is being removed) you could use ellipsis at the end of the line?

**Comment by balinterdi** [comment]
Thank you very much for reporting this (and the other issues). No, this wasn't deliberate, it probably "broke" when the syntax highlighting of code snippets was improved two publications before.

I fixed this by making the lines shorter (that's what the template linter demands, anyway) but I wonder if all the long lines are cut off that way.

Have you encountered instances where long lines are displayed correctly (Page 93 is not such an instance, unfortunately)?

**Comment by edsnowden** [comment]
p124 has a correctly-wrapping line.

**Comment by edsnowden** [comment]
p174 has some broken +/- formatting.

**Comment by edsnowden** [comment]
p189 is lacking diff colouring.
I think I'll stop reporting these, I reckon all code snippets will need to be given a quick check for the next version.
