### ISSUE TITLE
Version 20181123 - p115 dodgy indentation

### ISSUE THREAD

**Issue by edsnowden** [balinterdi/rarwe-issues#366]
The lines being removed in the first code snippet have been exdented by 3 indents.

**Comment by balinterdi** [comment]
Thank you. Weird that it's the only code snippet (as far as I can tell) that is broken like that. I had to manually insert some spaces so that it looks decent. Let me know if you find other instances of this.

**Comment by edsnowden** [comment]
Another instance on p161 (line 4).
