### ISSUE TITLE
Use this.routeName in this.modelFor calls to avoid duplication of route names

### ISSUE THREAD

**Issue by edsnowden** [balinterdi/rarwe-issues#368]
By page 139 the route code for bands.band.songs looks like this:

```
export default Route.extend({
    model () {
        return this.modelFor('bands.band');
    },

    resetController (controller) {
        controller.setProperties({
            isAddingSong: false,
            newSongTitle: ''
        });
    },

    actions: {
        didTransition () {
            let band = this.modelFor('bands.band');
            document.title = `${band.name} songs - Rock & Roll`;
        }
    }
});
```

I'm wondering - is there a good reason why you wouldn't do
```
    let band = this.model();
```
in the didTransition() action?

**Comment by balinterdi** [comment]
The problem with calling `this.model()` is that it will trigger a route transition when you're already at the end of the previous one.

That means you have to provide all the (route and query) params the model hook needs which is not straightforward and creates more duplication (the bad kind) than the route's name passed to `this.modelFor`.

It will also trigger the network requests if there are any. In the above case there are none but for example I build the `songs` router further in the Encore chapters and I do fire a network request to a `/songs` endpoint that does sorting, filtering and pagination. It's a relatively "expensive" request so the less we trigger it, the better.

That said, I agree that the fact that you have to write the route's name again is not ideal. There are a few ways to go about that:

1) `this.currentModel` – This is a private and undocumented property on the route so I wouldn't use it (especially in a book :) ) See [here](https://github.com/emberjs/ember.js/issues/11760) and [here](https://emberjs.com/api/ember/release/classes/Route?show=inherited%2Cprivate).
2) `this.controller.model` – That's better as we can be sure that `this.controller` is the actual controller (the setup happens in `setupController` and we're well past that.
3) `this.modelFor(this.routeName)` – That's the best as we still use `this.modelFor` which is the de-facto standard way to fetch models in routes and there's no duplication. `this.routeName` is also [public](https://emberjs.com/api/ember/3.5/classes/Route/properties/routeName?anchor=routeName). 

I'm so pleased with 3) that I'm actually going to change that in the book. Thanks for the suggestion that made me realize it's a better way.

**Comment by edsnowden** [comment]
Thanks for the explanation.

Out of interest (and bearing in mind that I don't know a lot about Javascript OO) by what mechanism does this.model() trigger a route transition? Our model() method doesn't call super(), so I had imagined that transitions call model(), not the other way around.

**Comment by balinterdi** [comment]
Sorry you're right, that part of my explanation was incorrect. It doesn't trigger a transition, it just calls the model hook (method).

**Comment by balinterdi** [comment]
And I should add that there's a way to trigger a route reload from the route itself – you have to call `this.reload()`.
