### ISSUE TITLE
p164 missing async? – explain the difference between details#save and songs#updateRating

### ISSUE THREAD

**Issue by edsnowden** [balinterdi/rarwe-issues#369]
I'm new to async/await and promises so this is perhaps more of a question than an issue. (BTW if you'd prefer me to use some other channel for queries let me know.)

On p162 we declare the save() method to be async, and await the song.save() call. However on p164 we don't declare the updateRating() method to be async, and simply return the song.save() call.

If I'm reading the MDN async documentation correctly (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function ) I think this means updateRating() will be returning a promise. (If updateRating() were async, then the return would implicitly await.)

Is this irrelevant to Ember (or indeed even desirable)?

**Comment by edsnowden** [comment]
Thanks for the clarification.

Does the caller of updateRating() expect a promise to be returned, or does it not care either way?

**Comment by balinterdi** [comment]
`updateRating` is an action that only gets called from the template (via an `action` helper) so it doesn't matter what it returns.
