### ISSUE TITLE
p171 http -> HTTP

### ISSUE THREAD

**Issue by edsnowden** [balinterdi/rarwe-issues#372]
I think I'd always capitalise HTTP in discursive text.

Having said that, in this particular context I wonder if HTTP is too general? Presumably Mirage doesn't stub out requests for CSS files etc, just REST/Ajax requests made by Ember Data?

**Comment by balinterdi** [comment]
Good point, thank you. I've modified `http requests` to `network requests` though even that is probably not precise enough. However, I think that's good enough, as this is what's commonly understood, I think.
