### ISSUE TITLE
p203 this.get('/bands/:id') was already added on p171

### ISSUE THREAD

**Issue by edsnowden** [balinterdi/rarwe-issues#378]
Line 5 of the code snippet already exists in the file by this point.

**Comment by balinterdi** [comment]
Did you close this because it's invalid?

**Comment by edsnowden** [comment]
Sorry - I closed it because the line after the snippet explained that we might have already added the line as part of an exercise for the reader. However, thinking about it, it was explicitly added on p171 - the exercise for the reader, iirc, was something to do with songs not bands.

**Comment by balinterdi** [comment]
Ok, so I'm going to re-open and investigate this. Thank you and happy holidays! :)
