### ISSUE TITLE
p222 no use made of button.rr-search-button

### ISSUE THREAD

**Issue by edsnowden** [balinterdi/rarwe-issues#383]
By the end of the chapter we've made no use of the search button added on page 216 - it has no action and is not in a form. Typing into the search box has immediate effect (which is cool) so the button seems to be completely redundant.

**Comment by balinterdi** [comment]
That's a very good point.

I just checked and no action is added to the button until the first chapter of the Encore book where we move the searching to the backend and trigger `updateSearchTerm` also on the click of the button (besides the `insert-newline` and `focus-out` actions of the input) so it plays some role there, especially on touch devices where it might be easier to click a button.

Let me give this some thought – I'll probably end up removing the button until it's needed but takes a lot of change in the code so it takes more time.
