### ISSUE TITLE
p232 loading template + nested routes seems hacky

### ISSUE THREAD

**Issue by edsnowden** [balinterdi/rarwe-issues#387]
It seems really inelegant to alter the URL-space of the website (i.e. introduce the meaningless /controls/ segment to the URL) to suit some quirk of the framework's loading implementation.

Is this a normal Ember pattern, or do people tend to use the loading action (to do something like toggle an isLoading boolean and make the spinner appear conditionally on this in the route's template)?

**Comment by balinterdi** [comment]
`/controls` doesn't appear in the URL as the corresponding path is set to an empty segment ('/`):

```js
Router.map(function() {
  this.route('bands', function() {
    this.route('band', { path: ':id' }, function() {
      this.route('controls', { path: '/' }, function() {
        this.route('songs');
      })
      this.route('details');
    });
  });
});
```

So *the name* of the songs route has changed to `bands.band.controls.songs` but the *the corresponding path* (URL) still stays `/bands/:id/songs`. That's a nice trick Ember developers employ.

It gives you a route with the related template where you can extract common elements and/or use the loading template if some data needs to be loaded for those elements but it doesn't mess with the URL structure.

Feel free to reopen if I missed something.
