### ISSUE TITLE
p240 URL remains unchanged on error

### ISSUE THREAD

**Issue by edsnowden** [balinterdi/rarwe-issues#388]
After following the book's RSVP method, I noticed that the URL doesn't change when the error template is displayed, which seems wrong. E.g. if I go to /bands then click Led Zeppelin it goes to /bands/1/details. If I then click the songs tab, the error template is shown but the URL still says details. This doesn't seem right - the /bands/1/details page is fine, it's /bands/1/songs that has a problem. I can imagine why this is - a failure in the model hook aborts the transition - but it doesn't seem great.

**Comment by balinterdi** [comment]
Until the transition to the new route has been fully completed the router doesn't change the URL, so I'm not sure if something can be done about that as this is very specific to Ember's router.
