### ISSUE TITLE
chapter 13 capitalizing should be done elsewhere

### ISSUE THREAD

**Issue by edsnowden** [balinterdi/rarwe-issues#390]
(This is just nitpicking really, I understand that chapter 13 is about helpers and not capitalising per se. Also, I've not got to the end of the book, so perhaps you come back to this later. But...)

As a full stack guy it would pain me to do the capitalising in the templates. I would sooner do it:

* in the database logic, i.e. as a normalisation of the data on the way into the persisted data model
* failing that, in the REST API that serves the data to clients
* failing that, in the client model layer (assuming Ember Data has hooks that allow this)
* and only as a last resort, in the display logic (i.e. the templates)

Even in the templates, I'd try to think about how to do it via semantic markup (e.g. some "this is a name" CSS class on a span around the name which causes the words to become capitalised).

Feel free to fire this annoying roadie!

**Comment by edsnowden** [comment]
Random thought - maybe a password strength meter? Although signup isn't until the next chapter.

**Comment by balinterdi** [comment]
That’s a good idea but a password-strength-meter would be a component, not a helper. A helper, in my view, is something that takes some input parameters and outputs a primitive value. It doesn’t handle inputs, doesn’t output DOM elements. inc, array, hash, i15n are good examples.

**Comment by edsnowden** [comment]
Ah apologies - I was actually thinking of a computed property to do the strength calculation, got that mixed up with helpers.

**Comment by balinterdi** [comment]
No worries, thanks for the idea and the feedback. Even though I closed the ticket for now, it'll be in the back of my mind pestering me – which is good as finding a better example would improve the content.
