### ISSUE TITLE
p255 first test failure is not about login route

### ISSUE THREAD

**Issue by edsnowden** [balinterdi/rarwe-issues#393]
When you say

> First, our test fails because our form includes a link to the login route (see the footer), which doesn't exist yet.

if what you mean by "first" is that this is the first error reported, it wasn't for me; when I got to running the tests, the first failure wasn't the missing login route but rather the missing signUp action. Specifically:

> Uncaught Error: Assertion Failed: An action named 'signUp' was not found in (generated sign-up controller)

I'm not sure what footer you're referring to. If you mean the text at the bottom of the red-bordered failed test div, that makes no reference to the login route that I can see:

<img width="1219" alt="screenshot 2018-12-27 at 12 14 19" src="https://user-images.githubusercontent.com/5147467/50480194-68f24200-09d2-11e9-8aaf-2dc2025f6b48.png">

**Comment by edsnowden** [comment]
Having resolved the signUp issue, I now get the missing login route error:

> Uncaught Error: Assertion Failed: You attempted to define a `{{link-to "login"}}` but did not pass the parameters required for generating its dynamic segments. There is no route named login

**Comment by balinterdi** [comment]
@edsnowden Hey, thanks so much! I'm pretty sure when I initially wrote/implemented this, that was the error I'd received but I now got them in the order you described. I've now fixed this.
