### ISSUE TITLE
chapter 14 services not explained

### ISSUE THREAD

**Issue by edsnowden** [balinterdi/rarwe-issues#399]
By the end of chapter 14 we've used services a few times (ajax, session) but these haven't really been explained. The syntax is pretty arcane:

```
import { inject as service } from '@ember/service';
...
export default Controller.extend({
    ajax: service(),
    // but then in some other controller
    session: service(),
});
```

This had me scratching my head - how can the same import, which is apparently a generic Ember service, be acting both as the Ajax service and as the session service? It was only then I remembered from one of the official Ember tutorials that there's some kind of weird javascripty introspection thing going on where the call to service() can somehow know the name of the variable it's being assigned to and use that as a default for its argument.

You've been pretty good about explaining the weird stuff so far so I wonder if this deserves a little paragraph.

**Comment by balinterdi** [comment]
Great point, thank you. I just added a backstage section about service injections.
