### ISSUE TITLE
P.59 - Code samples for Band creation missing song arrays?

### ISSUE THREAD

**Issue by alverion** [balinterdi/rarwe-issues#401]
On page 59 in the code samples (lines 45-48) it seems like the new band creation lines are missing arrays to pass into the song attribute... 

`let ledZeppelin = Band.create({ name: 'Led Zeppelin', songs: 
let pearlJam = Band.create({ name: 'Pearl Jam', songs:  
let fooFighters = Band.create({ name: 'Foo Fighters', songs: 
A([pretender]) });`

![ember pdf rendering](https://user-images.githubusercontent.com/1115132/50531022-d7113480-0ab8-11e9-8595-79614a96cb58.png)

however when I cut and paste the text I see the missing pieces:

`let ledZeppelin = Band.create({ name: 'Led Zeppelin', songs: A([blackDog]) }); 
let pearlJam = Band.create({ name: 'Pearl Jam', songs: A([yellowLedbetter, daughter]) }); let fooFighters = Band.create({ name: 'Foo Fighters', songs: A([pretender]) });
`

maybe something is not rendering properly in the pdf ? I confirmed that this content exists in the mobi file and is visible..  just not in the pdf ?

**Comment by balinterdi** [comment]
Indeed there are some rendering issues, some (most?) of which have been tracked at https://github.com/balinterdi/rarwe-issues/issues/363 .

I'm working on having the issue resolved in the next release.

And thank you for reporting it, it gives me one more test case to work with.
