### ISSUE TITLE
p289 why use computed() rather than init()?

### ISSUE THREAD

**Issue by edsnowden** [balinterdi/rarwe-issues#405]
Using computed() for the showErrors property was a bit baffling to me, especially as the accessors don't seem to be doing much except providing default values. So I tried just

```
        showErrors = {
            email: false,
            password: false,
        },
```

This didn't work of course, because I'd forgotten that Ember doesn't allow objects for property initialisation. (BTW Visual Studio Code's editor tells you this immediately, nifty.) You explain this on p87, but the solution in that section of the book is to use the controller's init() hook, so I tried that:

```
    init () {
        this._super(...arguments);
        this.showErrors = {
            email: false,
            password: false,
        };
    },
```

That seems to work (the tests pass, and interactively the messages appear and disappear as expected), so I'm wondering whether there's some problem with the init() approach which means we need to use computed()? Presumably using computed() defers creation of the initial object until it's needed, but that seems like a marginal benefit given the {{#if showErrors.email}} in the template will immediately trigger it.

If the init() approach is fine too - why didn't I need to create the object as an Ember.Object, which I thought I might need to do so it's observable? Am I just getting away with it somehow?

If the init() approach is problematic here - why wasn't it in the earlier case on p86?

**Comment by balinterdi** [comment]
@edsnowden You're totally right, init is way simpler. Not sure why I opted for the CP with a custom setter in the first place 🤷‍♂ . Thank you for pointing this out.
