### ISSUE TITLE
StarRating onclick on anchor vs. label

### ISSUE THREAD

**Issue by CodingItWrong** [balinterdi/rarwe-issues#408]
In the components chapter, `setRating` is called when you click on a `<label>`:

<img width="952" alt="screen shot 2019-01-14 at 4 08 02 pm" src="https://user-images.githubusercontent.com/15832198/51144547-fa591500-1816-11e9-962c-e7c02461e5d1.png">

But in the testing chapter, it's called when you click on an anchor tag:

<img width="952" alt="screen shot 2019-01-14 at 4 07 45 pm" src="https://user-images.githubusercontent.com/15832198/51144560-08a73100-1817-11e9-8d65-1b467e142927.png">

**Comment by balinterdi** [comment]
@CodingItWrong And I'd recently converted them to `<span>s` so it's all spans now :) Thank you.
