### ISSUE TITLE
Missing fillIn import

### ISSUE THREAD

**Issue by CodingItWrong** [balinterdi/rarwe-issues#410]
In the query params chapter under "Adding a dash of query parameters", the following import statement appears:

<img width="519" alt="screen shot 2019-01-14 at 7 20 19 pm" src="https://user-images.githubusercontent.com/15832198/51151731-75c7c000-1831-11e9-94f8-f9740653295e.png">

However, in section "Filtering songs by a search term" we added "fillIn" to that import, so the full import statement should be:

```
import { visit, click, fillIn, currentURL }…
```

**Comment by balinterdi** [comment]
Thank you, that'd been reported and fixed and will be published with the next release.
