### ISSUE TITLE
Hitting save on description button firing mirage error?

### ISSUE THREAD

**Issue by ShaheensWeb** [balinterdi/rarwe-issues#413]
```
export default function() {
    this.get('/bands');
    this.post('/bands');
    this.get('/bands/:id')
    this.get('/bands/:id/songs'); 
}

```
Mirage block is above - but when I hit save on the description I get: 

`"Mirage: Your Ember app tried to PATCH '/bands/1',
         but there was no route defined to handle this request.
         Define a route that matches this path in your
         mirage/config.js file. Did you forget to add your namespace?"`

**Comment by ShaheensWeb** [comment]
Not quire sure how to move forward here - Happened around page 200 and can't seem to resolve it - i assumed /bands/:id would cover the error case of /bands/1

**Comment by balinterdi** [comment]
You need to add `this.patch('/bands/:id')` to the Mirage handlers but it shouldn't be necessary so I'm going to take a look this coming week. Can you tell me which page it's on?

**Comment by ShaheensWeb** [comment]
I was on page 187-190 range when I decided simply that I wasn't going to add all the types of tests and just continue reading - then I loaded the app up and essentially noticed the config/mirage.js was definitely missing stuff just based off the logged errors in console 

I added what you said it worked - still having an issue with songs but I think I resolve it myself (just needs a post for /songs)

**Comment by ShaheensWeb** [comment]
Exact location: top of page 187 is when I decided to reload the app

**Comment by ShaheensWeb** [comment]
Thanks again @balinterdi appreciate your time

**Comment by balinterdi** [comment]
Sorry, just coming back to this to make sure that what's in the book works fine. Can you confirm this? Thank you.

**Comment by ShaheensWeb** [comment]
@balinterdi no biggie - i found following the book to a T this error logged around page 187-190: 

"Mirage: Your Ember app tried to PATCH '/bands/1', but there was no route defined to handle this request. Define a route that matches this path in your mirage/config.js file. Did you forget to add your namespace?"

I haven't had time due to work to check but I MAY have missed the declaration of:

`this.patch('/bands/:id')`

in the book - if its not there though should definitely be added


Have a great day!

**Comment by balinterdi** [comment]
I've taken a look and found that we have no tests at that point that would make it necessary. If we triggered the save button after updating the band's description we'd indeed need to have that route handler but as far as I could see we don't write that test in the book.

Let me know if I'm missing something.

**Comment by balinterdi** [comment]
@ShaheensWeb Can you provide more details about how that's possible? Or, can I close this?
