### ISSUE TITLE
Copyedits for clarity consideration

### ISSUE THREAD

**Issue by amyrlam** [balinterdi/rarwe-issues#420]
Ch 3 pdf, page 22
* (1) Update Ember Inspector image
* (2) Update console error message

![image](https://user-images.githubusercontent.com/1372946/57352999-fb8eb480-711b-11e9-8aba-5b3e8bd3529f.png)

***

Ch 3 pdf, page 25
* Consider including L3-L4 for clarity or add a `...`?

![image](https://user-images.githubusercontent.com/1372946/57353072-2c6ee980-711c-11e9-9b6e-07298d008867.png)

***

Ch 4 pdf, page 36
* `.hbs` indentation mistakenly jumped to 4 

![image](https://user-images.githubusercontent.com/1372946/57353140-62ac6900-711c-11e9-916d-b7ff8df797ab.png)

**Comment by balinterdi** [comment]
Hey Amy,

Thank you very much for these fixes.

I fixed all of them but the 

> (2) Update console error message

It seems to me like the error message didn't change compared to what is in the book now. Am I missing something?

**Comment by amyrlam** [comment]
Cool, thanks for making the fixes - great book! 

Oh, it was a small change, set vs. Ember.set:

IS: 
![image](https://user-images.githubusercontent.com/1372946/58361927-c2a64d80-7e46-11e9-98cb-c1ef71aa988c.png)

SHOULD BE: 
![image](https://user-images.githubusercontent.com/1372946/58361937-d6ea4a80-7e46-11e9-9c29-442430e68be2.png)
