### ISSUE TITLE
Copyedit: potential printing bug(?) where file type separated from code sample

### ISSUE THREAD

**Issue by amyrlam** [balinterdi/rarwe-issues#421]
Seems to happen when it's at the bottom of the page?

(1) Ch 5 pdf, page 50

<img width="832" alt="Ch 5 pdf, page 50" src="https://user-images.githubusercontent.com/1372946/57403751-3aaa1d80-718f-11e9-944c-3ce8ea18f204.png">

(2+) Ch 5 pdf, page 54, also pages 59, 62 bottom corner

<img width="853" alt="Ch 5 pdf, page 54, also 59, 62 bottom corner" src="https://user-images.githubusercontent.com/1372946/57403753-3da50e00-718f-11e9-82f0-e51a7fd5cda0.png">

**Comment by balinterdi** [comment]
Thank you. This was a regression that I've now hopefully fixed.
