### ISSUE TITLE
Typo in PJ song title

### ISSUE THREAD

**Issue by bazzel** [balinterdi/rarwe-issues#424]
Not a big deal (unless you're a PJ fan 😉), but the PJ song 'MVC' should be 'MFC'. It's mentioned in Ch. 13 _Helpers_ under _Capitalizing each word of a name_.

**Comment by balinterdi** [comment]
Not a big deal you say?! Being a true Pearl Jam fan, I'm deeply offended 🗡 

Joking aside, thank you for spotting this, I've now fixed it (and I'm ashamed of myself).
