### ISSUE TITLE
Duplicate words

### ISSUE THREAD

**Issue by bazzel** [balinterdi/rarwe-issues#425]
Ch. 15, par. _Showing the errors at the right moment_:
> First of all, we have set up validation to happen on the on the User model...

Should be:
> First of all, we have set up validation to happen on the User model...

Ch. 16, par. _Setting environment variables_:
> Each snapshot has a unique name and Percy uses these to to detect visual changes...

Should be:
> Each snapshot has a unique name and Percy uses these to detect visual changes...

**Comment by balinterdi** [comment]
Thanks, Patrick, I've now fixed these.
