### ISSUE TITLE
400 Bad Request - PATCH (Band Details) 

### ISSUE THREAD

**Issue by DeclanBoller** [balinterdi/rarwe-issues#428]
I'm finding that saving and fetching band/song data works as expected. However editing and saving a bands details returns a 400 bad request from the server. 

Not sure what I can do on my end for this one... 

<img width="981" alt="Screen Shot 2019-06-03 at 9 53 56 am" src="https://user-images.githubusercontent.com/38486207/58769117-15ba9600-85e7-11e9-9aaf-8a910dd8f7b5.png">

**Comment by balinterdi** [comment]
Sorry about that, I'm going to look into it.

Can you let me know

1) Which chapter and section are you hitting this error in?
2) The detailed error message you see on the console? Is that all you see or are there more details in the response (or on the dev console)?

I tried to update a band on the same URL via Postman but the request the app makes might be different (hence my first question).

Thank you.

**Comment by DeclanBoller** [comment]
Hey thanks for the response. 

I noticed it after Ch. 9 - Updating a Bands Description. I've attached a snapshot of the headers, but other than that this is the only significant information I can see of relevance. 

![Uploading Screen Shot 2019-06-04 at 9.26.00 am.png…]()

**Comment by balinterdi** [comment]
I checked out that chapter and ran the app with the following command (as mentioned in the book):

    ember serve --proxy=http://json-api.rockandrollwithemberjs.com

I tried filling in the band details for Led Zeppelin (and then also Pearl Jam, just to make sure I'm looking at the same thing) and it has just worked.

Request:
https://cl.ly/ef1785519ede

Response:
https://cl.ly/6e8292992cb2

I also looked into the logs to see your failed PATCH request but couldn't find it.

Can you share the request payload (the actual data that's sent as the new serialized version of the band)?

**Comment by DeclanBoller** [comment]
Sure, please see attached image. 
<img width="976" alt="Screen Shot 2019-06-11 at 8 56 26 am" src="https://user-images.githubusercontent.com/38486207/59232340-432ac380-8c27-11e9-9550-8f6ff996de87.png">

**Comment by balinterdi** [comment]
@DeclanBoller Just to make sure, are you passing the `--proxy` option as I describe above?

**Comment by DeclanBoller** [comment]
Yes, I am. @balinterdi

**Comment by balinterdi** [comment]
I checked out your fork, ran the app with the above command and it has all worked for me.

I could update the details for both Pearl Jam and Led Zeppelin.

https://cl.ly/107820d9a4b5
https://cl.ly/b5421b2c1e8f

Have you tried it multiple times? What I can think of is that the API was down/throwing fits when you tried this and it now works (though I didn't deploy a new version so I'd be surprised).
