### ISSUE TITLE
add example of simple flask-json-restapi server

### ISSUE THREAD

**Issue by antonbezkrovny** [balinterdi/rarwe-issues#434]
Hi!

this could be useful for Python readers
[Flask server](https://gist.github.com/antonbezkrovny/226d3e1c63c8f578affe3ea78465198f)

with some updates in 

```
//app/adapters/application.js

import DS from 'ember-data';

export default DS.JSONAPIAdapter.extend({
  host: 'http://localhost:5000'
});
```

```
// app/models/band.js

import DS from 'ember-data';

const { Model, attr, hasMany } = DS;


export default Model.extend({
  name:         attr('string'),
  description:  attr('string'),
  **songs**:        hasMany('song'),
});
```

```
//app/models/song.js

import DS from 'ember-data';

const { Model, attr, belongsTo } = DS;

export default Model.extend({
  name: attr('string'),
  rating: attr('number'),
  **bands**: belongsTo('band')
  });

```

**Comment by balinterdi** [comment]
iirc the way this is set up in the book is that `host` is unset in development and xhr/fetch requests are proxied to whatever was passed from the command line to the `--proxy` argument.

Also, I could add examples for each popular back-end framework but that'd be a lot and the book doesn't have a focus on any of these frameworks.
