### ISSUE TITLE
dasherize not imported, chapter 6, p. 94

### ISSUE THREAD

**Issue by edflips** [balinterdi/rarwe-issues#438]
Hello!

Book version: 20190913
Chapter 6: Controllers
Page 94

The dasherize method is used for the first time here, but it isn't shown as imported in the diff.

```javascript
import { dasherize } from '@ember/string';
```

**Comment by balinterdi** [comment]
Good catch, thank you. I've now fixed this.

**Comment by balinterdi** [comment]
I usually keep issues open until the next release because other people might stumble across the same problem and then they see it's already fixed. So I've reopened this one, too.

**Comment by PUncle** [comment]
Ah ok, understood, thanks!
