### ISSUE TITLE
Chapter 8 - Setting descriptive page titles -  ReferenceError: capitalize is not defined

### ISSUE THREAD

**Issue by RussellSnyder** [balinterdi/rarwe-issues#441]
I get an error when I use this code that capitalize is not defined.

<img width="788" alt="Screen Shot 2019-11-17 at 3 24 26 PM" src="https://user-images.githubusercontent.com/7914218/69008750-6122ef80-094e-11ea-9e68-16c65264fe4d.png">

adding 
```
import { capitalize } from '@ember/string';
```
at the top fixed this issue

**Comment by balinterdi** [comment]
Thanks!
