### ISSUE TITLE
Chapter 8 - Warning about losing data - action is not defined

### ISSUE THREAD

**Issue by RussellSnyder** [balinterdi/rarwe-issues#442]
When using the detail controller provided

<img width="772" alt="Screen Shot 2019-11-17 at 3 33 48 PM" src="https://user-images.githubusercontent.com/7914218/69008875-b14e8180-094f-11ea-9f8d-0e4afa92fe40.png">

I get various errors saying something about action not being defined.
adding 
```
import { action } from '@ember/object';
``` 
to the top fixes this error

**Comment by balinterdi** [comment]
Thanks, Russell!
