### ISSUE TITLE
Chapter 10 - data-test-rr="new-band-input" already declared

### ISSUE THREAD

**Issue by RussellSnyder** [balinterdi/rarwe-issues#444]
Small inconsistency, but actually the 'new' data-test-rr attribute in chapter 10, here:

<img width="753" alt="Screen Shot 2019-11-17 at 7 09 32 PM" src="https://user-images.githubusercontent.com/7914218/69011724-e1a51880-096d-11ea-81b2-18db3d5eba87.png">

was first declared a few chapters earlier:

<img width="841" alt="Screen Shot 2019-11-17 at 7 08 46 PM" src="https://user-images.githubusercontent.com/7914218/69011743-1022f380-096e-11ea-9542-363c5f51232a.png">

and show up again here:

<img width="758" alt="Screen Shot 2019-11-17 at 7 12 57 PM" src="https://user-images.githubusercontent.com/7914218/69011775-524c3500-096e-11ea-909c-2e27189308e2.png">

A quick grep through the book shows that this test tag is already in the code examples twice before it is explained in chapter 10.  I would suggest removing them from the earlier two examples for consistency.

**Comment by balinterdi** [comment]
Wow, great spot, thank you!
