### ISSUE TITLE
Chapter 10 - this.updateRating not working 

### ISSUE THREAD

**Issue by RussellSnyder** [balinterdi/rarwe-issues#445]
When I run the tests here: 

<img width="766" alt="Screen Shot 2019-11-17 at 7 50 08 PM" src="https://user-images.githubusercontent.com/7914218/69012218-aa396a80-0973-11ea-9b96-ce671edafc7e.png">

I get an error that this.updateRating is undefined.

I solved this by using this.actions.updateRating like so:
```
    await render(hbs`<StarRating @rating={{song.rating}} @onClick={{fn this.actions.updateRating song}} />`);
```

not sure if this is the best way, but it works and hooks into the action function as intended and leads to passing tests

**Comment by balinterdi** [comment]
Thanks a bunch. It can be done even simpler:

```js
  test('The setRating action', async function(assert) {
    this.set('song', EmberObject.create({ rating: 3 }));
    this.set('updateRating', function(song, rating) {
      song.set('rating', rating);
    });
    await render(hbs`<StarRating @rating={{song.rating}} @onClick={{fn this.updateRating song}} />`);
    await click('[data-test-rr=star-rating-5]');
    assert.equal(this.get('song.rating'), 5, "The clicked star's rating is correctly sent");
  });
```

Since we run everything in the same context (the context of the test), there's no need to wrap our handler function (`updateRating`) with the `action` method.

Thanks for pointing this out!
