### ISSUE TITLE
Chapter 2 - Mention the correct `ember-cli` version previously installed

### ISSUE THREAD

**Issue by MrChocolatine** [balinterdi/rarwe-issues#448]
With the book version `20190913`.

Chapter 2, page 11

You recommend to install `ember-cli@3.12.0` :

![aa](https://user-images.githubusercontent.com/47531779/71779981-d14c0a00-2fbc-11ea-8f8a-b8aea7afd09c.png)

But at the end of the same page you are referring to `ember-cli@3.10.1`:

![bb](https://user-images.githubusercontent.com/47531779/71779984-da3cdb80-2fbc-11ea-809e-d710ad2d179a.png)

We should see instead :
> ...
> The npm install -g ember-cli@3.12.0 step above should have taken care of this
> ...

**Comment by balinterdi** [comment]
Hey Maxime. Thank you, that was an oversight, it should be 3.12.0 in the second place, too. I've fixed and it will go out in the next update.

Actually, the next update should be 3.15 which I expect to release pretty soon, but I've now amended that phrase to "the `npm install` step" so it should work for all versions :)
