### ISSUE TITLE
Chapter 6 - old `actions` hash mentioned while using `action` function wrapper

### ISSUE THREAD

**Issue by MrChocolatine** [balinterdi/rarwe-issues#449]
With the book version `20190913`.

Chapter 6, page 76.

You use the `action()` function wrapper but right after you mention the old `actions` hash :
![aa](https://user-images.githubusercontent.com/47531779/71786775-cbcbdf80-300f-11ea-8278-4d43584d342d.png)

As the next update will be based on Ember 3.15, I guess the `@action`decorator will be recommended (as it is on the official documentation), or even if you want to stick with `action` as a function wrapper, I don't think this sentence should be kept (= reformulated) for this version.
> As you can see, actions need to be defined in a top-level `actions hash

It does not add any value considering the paragraph just above (page 75) :
> What this means is that if we want to use a function as an action-handler for its template, we need to bound its this. That's done by marking it as action – which will do exacly that: bind the current context so that it can be used as an action handler in the template. Contrary to what the message tells us, using the `@action` decorator doesn't work just yet. We should use action as a function wrapper:

On a side note, in this paragraph :
- Small typo `exacly` => `exactly`
- I guess the sentence `Contrary to [...] use action as a function wrapper` will also be removed.

**Comment by balinterdi** [comment]
Maxime,

Thank you so much for the detailed issue description and suggestions. I've now fixed this and it will be soon released in version 3.15.

Regarding the complete octanification of the book, see [my recent post](https://www.balinterdi.com/blog/psa-on-rock-roll-with-ember-octane/).

**Comment by MrChocolatine** [comment]
> Maxime,
> 
> Thank you so much for the detailed issue description and suggestions. I've now fixed this and it will be soon released in version 3.15.
> 
> Regarding the complete octanification of the book, see [my recent post](https://www.balinterdi.com/blog/psa-on-rock-roll-with-ember-octane/).

Happy to help :v: .
