### ISSUE TITLE
Page 139 I can't get the controller to reset

### ISSUE THREAD

**Issue by lenoraporter** [balinterdi/rarwe-issues#456]
I put the resetcontroller logic in `app/controller/bands/band/songs.js` but it doesn't work. The example is stating it goes in `app/routes/bands/band/songs.js` but I don't believe we created a `bands/bands/songs.js` file in routes. 

I'm using version 20200120.

**Comment by balinterdi** [comment]
Hey Lenora,

`resetController` is a route hook, so it should definitely go in `app/routes/bands/band/songs.js`. We created that file manually in the Nested routes chapter, page 60:

<img width="816" alt="Screenshot 2020-05-20 at 22 43 13" src="https://user-images.githubusercontent.com/5022/82495391-5149bb00-9aeb-11ea-89c5-9bbf8de1093d.png">

**Comment by lenoraporter** [comment]
Ahh! I must've missed this step. Thanks Balint!

**Comment by lenoraporter** [comment]
Just tried it. It works!
