### ISSUE TITLE
Ember Data has been released.

### ISSUE THREAD

**Issue by russap** [balinterdi/rarwe-issues#47]
In chapter 1, last paragraph of "The missing M from MVC", it states that Ember Data 1.0 will be released soon. It hasn't been updated to reflect the fact that Ember Data was released back around June 18.

**Comment by balinterdi** [comment]
Thank you for spotting this. The whole paragraph will need to be rewritten very soon to reflect that Ember Data is the official library and will be kept in lockstep with Ember.

**Comment by balinterdi** [comment]
The updated paragraph will be:

> For quite a while, the notable missing piece from Ember was the “M” from MVC,
the model layer. There were [several](https://github.com/emberjs/data)
[model](https://github.com/ebryn/ember-model) [libraries](http://epf.io/) that
could fill that hole, while certain applications (the biggest of which is
[Discourse](http://www.discourse.org/), the flagship OS Ember application)
chose to implement their own.

> The reason for not having a "persistence" layer implementation built into the
core is probably the fact that it is the most easily separable piece of
architecture.

> That said, [Ember Data](https://github.com/emberjs/data) can now be considered
the official Ember model layer, and starting from version 1.13, they are in
lockstep, so their latest stable (major and minor) versions are the same.
Ember 2.3, for example, will be most perfectly matched by Ember Data 2.3.
