### ISSUE TITLE
Reference song model

### ISSUE THREAD

**Issue by camskene** [balinterdi/rarwe-issues#6]
On page 24 of the PDF it is stated 'we can just copy and paste the content from the previous section. This gives the impression that the code is the same. However, there is a crucial difference where `song` is referenced on this page and not `model`. 

```
<ul>
  {{#each song in songs}}
    <li>{{song.title}} by {{song.band}} ({{song.rating}})</li>
  {{/each}}
</ul>
```

Previous section
```
<ul>
{{#each song in model}}
  <li>{{song.title}} by {{song.band}} ({{song.rating}})</li>
  {{/each}} 
</ul>
```

**Comment by balinterdi** [comment]
Thank you, Cam, I just fixed this, will go out in the next update!
