### ISSUE TITLE
Computer Properties Backstage Code Doesn't Work in Console

### ISSUE THREAD

**Issue by jimjimovich** [balinterdi/rarwe-issues#63]
The code for the Computer Properties section starting on page 67 does not work in the console. The JSBin http://emberjs.jsbin.com/cebiwa/edit also doesn't give correct output in the console.

When running in the console, 
var band = Band.create({ name: "Mookie Blaylock", language: 'jsp' });
returns an undefined error.

**Comment by balinterdi** [comment]
Hmm, not sure what's going on. I just ran your emberjs JSBin and it worked perfectly:

![screen shot 2015-08-24 at 18 37 04](https://cloud.githubusercontent.com/assets/5022/9445986/645edae2-4a8f-11e5-8c33-1aaa9d343aff.png)

I also created a new band to see if it comes back as undefined but it does not:

![screen shot 2015-08-24 at 18 38 10](https://cloud.githubusercontent.com/assets/5022/9445997/77502804-4a8f-11e5-8ff1-83e918444b24.png)

True, something prints undefined when the new band is created but the returned band behaves correctly (which I "prove" by printing its `site` property).

Let me know if I've misunderstood something.
