### ISSUE TITLE
Router.reopen in start-app.js throws error

### ISSUE THREAD

**Issue by vikram-s-narayan** [balinterdi/rarwe-issues#68]
In the book (page 177 of book version dated Aug, 7), there is this line: 

  Router.reopen({
    location: 'none'
  });

which throws an error. 

Needs to be removed.

**Comment by balinterdi** [comment]
Vikram, thank you very much. This must have changed somewhere along the line. The code no longer contained it but the code snippet you pointed out did. This will be fixed in the next book update.
