### ISSUE TITLE
Repo for example in book?

### ISSUE THREAD

**Issue by camskene** [balinterdi/rarwe-issues#7]
Hey, could you provide an accurate example repo for the app created in the book?

I've been over it many times and can't get the songs to display in the right hand column.

**Comment by balinterdi** [comment]
You get access to the code repository of the application if you purchase the middle- or high-tier packages.

That said, customers of the low-tier ("Smoke on the Water") package should be able to build up the application by themselves and things should just work with the snippets in the book. Can you tell me which chapter you got stuck at, what error (if any) you see and provide me the code that you have for the band.songs template and route? (in the first step)

**Comment by balinterdi** [comment]
@camskene Could you make progress? I edited several sections in Chapter 5 to make it easier to work along with just the book. I'll release an update hopefully next week but I would like to know if the problem you experienced is now resolved or whether I can make improvements there.

**Comment by balinterdi** [comment]
@camskene Just released a new version. Please let me know if you still have those issues. Thank you.
