### ISSUE TITLE
"setRating" should be "setSorting"

### ISSUE THREAD

**Issue by vikram-s-narayan** [balinterdi/rarwe-issues#70]
Page 211 of book (version dated Aug 7, 2015) says, "Having the sorting implemented through links has the advantage that no actions need to be
defined (so setRating can be removed from the controller) and that when one hovers over the
buttons, the URL is displayed just as with "ordinary" links."

It should be "so setSorting can be removed from the controller".

**Comment by balinterdi** [comment]
Thank you, Vikram, for your sharp eye, fixed!
