### ISSUE TITLE
Acknowledgements: Paragraph out of place (epub version)

### ISSUE THREAD

**Issue by morganick** [balinterdi/rarwe-issues#73]
<img width="1040" alt="screenshot 2015-09-07 10 45 19" src="https://cloud.githubusercontent.com/assets/151139/9718943/0ae6dd74-554e-11e5-88c7-9f49eceea4cc.png">

**Comment by balinterdi** [comment]
Thank you for this, I use a script to fill in the many names from a list and I did not run that script for the epub version :) This will be fixed in the next release, that should be coming out this week.
