### ISSUE TITLE
Backstage - Handlebars' fail-softness: Missing example

### ISSUE THREAD

**Issue by morganick** [balinterdi/rarwe-issues#74]
<img width="1069" alt="screenshot 2015-09-07 15 22 32" src="https://cloud.githubusercontent.com/assets/151139/9722073/834bfef4-5574-11e5-8ef1-91bc25d0fadf.png">

**Comment by balinterdi** [comment]
Very nice catch, thank you, Nick!

The code snippet was unescaped, it's supposed to be this:

```handlebars
{{band.manager.address.street}}
```
