### ISSUE TITLE
p.203... protect against extra spaces

### ISSUE THREAD

**Issue by andrewjdavison** [balinterdi/rarwe-issues#79]
I got caught on this for a while. If you have spaces in the "options" strings, the param extraction wont work.

Could be worth a cautionary note to not have spaces, or better practice to strip the spaces from the strings, like this perhaps...

  return options[this.get('sortBy')].replace(/ /g,'').split(',');

**Comment by balinterdi** [comment]
I'm a bit on the fence about this one since you, as the developer of the app, have control over the strings and so I find the regex replace a bit distracting. Nevertheless, you are right that people following along can get tripped up by this so I added the cautionary note you suggest. Thank you!
