### ISSUE TITLE
Tests: Registering a Synchronous Helper - Restart ember serve after modifying .jshintrc

### ISSUE THREAD

**Issue by mtudor** [balinterdi/rarwe-issues#81]
New to JSHint and Ember so I might just have this wrong, but when I added the assertion helpers to .jshintrc, it didn't stop the complaining about helpers not being defined until I *restarted ember serve*.

    { "predef": [
            (...)
            "assertTrimmedText",
            "assertLength",
            "assertElement",
        ]
    }

Might be worth a mention if this is indeed required as I got stuck for a little trying to figure out what I'd missed!

**Comment by mtudor** [comment]
Ah, you say that this is required when writing the async helpers - probably just needs the same caveat earlier.

**Comment by balinterdi** [comment]
Thank you, Mark, good catch! I now mention it in both places.
