### ISSUE TITLE
JSHint: x is defined but never used

### ISSUE THREAD

**Issue by mtudor** [balinterdi/rarwe-issues#82]
Throughout the Test section, there are instances where I am being told by JSHint (for example):
    helpers/async-helpers.js: line 10, col 32, 'context' is defined but never used.

I've just been removing the unneeded parameter or faking the use of it (context = context) to avoid the message, but I'm sure if I looked into it there might be a better way.

It might be worth a mention if there is, or at least a recognition that the reader will see these errors?

**Comment by balinterdi** [comment]
Thank you, Mark, that's a good point, I'll mention it in the next release.

**Comment by mtudor** [comment]
Good stuff - on another note, really enjoying the book and feel like it's a great introduction to Ember so many thanks for all your efforts on it! :)

**Comment by balinterdi** [comment]
Thank you, I've now added a paragpraph about how to suppress these warnings. You can do the same by setting `unused: false` in `tests/.jshintrc`. The `vars` setting for `unused` would even be better but I couldn't make it work in Ember CLI.

**Comment by mtudor** [comment]
Great stuff @balinterdi!  Happy I could help and thanks for the pointer in these comments - saves me searching the book :)
