### ISSUE TITLE
Unit tests in Ember (pg 190) is missing feature implementation

### ISSUE THREAD

**Issue by dwayne** [balinterdi/rarwe-issues#84]
I read straight through the book up to this point so I don't think I missed the implementation of the matching songs feature. The unit test you write are for a feature yet to be implemented and so we end the chapter with a failing test case. It's not clear if that is intended or if we are to wait till later on to see the implementation of the feature and hence passing unit tests.

**Comment by balinterdi** [comment]
You are completely right, Dwayne, I'll fix this for the next edition. Thank you!

**Comment by balinterdi** [comment]
If you would like to proceed before I publish the next version (2.0 on Thursday!), here is the unit test I wrote for the chapter:

```js
// tests/unit/controllers/bands/band/songs-test.js
import Ember from 'ember';
import {
  moduleFor,
  test
} from 'ember-qunit';

moduleFor('controller:bands/band/songs', 'BandsBandSongsController');
test('canCreateSong', function(assert) {
  assert.expect(3);

  var controller = this.subject();
  var band = Ember.Object.create();
  controller.set('model', band);

  controller.set('songCreationStarted', false);

  assert.ok(!controller.get('canCreateSong'), "Can't create song if process has not started and no songs yet");

  controller.set('songCreationStarted', true);

  assert.ok(controller.get('canCreateSong'), "Can create song if process has started");

  controller.set('songCreationStarted', false);
  var songs = [
    Ember.Object.create({ id: 1, title: 'Elephants', rating: 5 }),
  ];

  band.set('songs', songs);
  assert.ok(controller.get('canCreateSong'), "Can create song if process has not started but there are already songs");
});
```

Thank you, again, that was a great catch.

**Comment by dwayne** [comment]
No problem @balinterdi. I've since finished the book and overall I found it to be an excellent introduction to [Ember.js](http://emberjs.com/).

**Comment by balinterdi** [comment]
Thank you, Dwayne!
