### ISSUE TITLE
`Ember.SortableMixin` appears to be deprecated in Ember 2.0

### ISSUE THREAD

**Issue by jluckyiv** [balinterdi/rarwe-issues#85]
In the Routing chapter (location 1283 in Kindle), the following fails for me after updating to Ember 2.0:

```javascript
// app/routes/songs.js

// code

var SongCollection = Ember.ArrayProxy.extend(Ember.SortableMixin, {
  // code
});
```

`Ember.SortableMixin` appears to [be deprecated](http://discuss.emberjs.com/t/replacing-sortablemixin-in-2-0/8574).

**Comment by balinterdi** [comment]
Good catch, I've fixed this in the Templates chapter, but not here, will do soon.

**Comment by jluckyiv** [comment]
I love the book. And thanks for the 2.0 upgrade. So continue to use the `Ember.computed.sort` from the Templates chapter?

**Comment by jluckyiv** [comment]
The same problem appears in the Nested routes chapter with the `BandsCollection`.

**Comment by balinterdi** [comment]
Yep, I'm already on it :+1:
