### ISSUE TITLE
Small conflict in `bower.json` file after installing Bootstrap

### ISSUE THREAD

**Issue by jluckyiv** [balinterdi/rarwe-issues#86]
There is a small conflict in the `bower.json` file between the Ember-CLI chapter and the Templates chapter. In the Ember-CLI chapter, the dependencies are `ember` 2.0.2, `ember-cli-shims` 0.0.4, and `ember-load-initializers` 0.1.6. In the Templates chapter, they are `ember` 2.0.0, `ember-cli-shims` 0.0.3, and `ember-load-initializers` 0.1.5.

**Comment by balinterdi** [comment]
I updated the Ember CLI chapter in rushing mode and forgot that there is one more instance where the dependencies are thus listed.

Thanks a lot!
