### ISSUE TITLE
Ember.SortableMixin not in Ember 2.0

### ISSUE THREAD

**Issue by dbouwman** [balinterdi/rarwe-issues#88]
I just bought the book yesterday and got the "patch" update that adds details to update Ember to 2.0, and started working through the book this afternoon (on 2.x)

I fas following along with the code and got an error on this:
```
var SongCollection = Ember.ArrayProxy.extend(Ember.SortableMixin, {  
 sortProperties: ['rating'],  
 sortAscending: false,   
content: [] 
});
```

I did some quick googling and found this thread http://discuss.emberjs.com/t/replacing-sortablemixin-in-2-0/8574 indicating that `Ember.SortableMixin` was removed from 2.x but no deprecation message was ever given.

Anyhow - I've been moving forward using `Ember.computed.sort` as shown in the BandsCollection below

```
var BandsCollection = Ember.Object.extend({
  content:[],
  sortProperties:['name:desc'],
  sortedContent: Ember.computed.sort('content','sortProperties')
});
```

This has required a few minor changes around the code, mainly using `bands.get('content')...` instead of just `bands`

**Comment by balinterdi** [comment]
Sorry about this, I rushed out an update on 10/02 and I was not careful enough to realize there are two more instances of the now defunct SortableMixin. I'll send out the updated copy soon.
