### ISSUE TITLE
Page 129  <...> beforeModel and model hooks are skipped

### ISSUE THREAD

**Issue by ivanvotti** [balinterdi/rarwe-issues#93]
Official documentation says only `model` hook is skipped: http://guides.emberjs.com/v1.10.0/routing/asynchronous-routing/

The book says:
If the route has a dynamic segment (bands.band in our case has :slug) and the context object (the band object) is passed in, the `beforeModel` and `model` hooks are skipped.

**Comment by balinterdi** [comment]
Thanks a lot, Ivan!

I'm pretty sure `beforeModel` was skipped at one point in the Ember series, but I double-checked for the current app, and indeed, it is no longer skipped.
