### ISSUE TITLE
Page 132 (PDF) Ember.$(document).attr

### ISSUE THREAD

**Issue by ivanvotti** [balinterdi/rarwe-issues#94]
```Ember.$(document).attr('title', `${band.get('name')} songs - Rock & Roll`);```

can be changed to:

```document.title = `${band.get('name')} songs - Rock & Roll`;```

**Comment by balinterdi** [comment]
Thank you, Ivan. I wasn't sure if there are any browser inconsistencies which jQuery might do away with. I've changed all the occurrences to the simpler form.

**Comment by ivanvotti** [comment]
Thank you for your great book and for the fix. It would be good to remove `(Ember.$() is an alias for jQuery's top-level variable)` as it doesn't make sense in that context anymore (page 131, PDF).

<img width="534" alt="screenshot 2015-10-17 10 54 53" src="https://cloud.githubusercontent.com/assets/1476221/10556904/3e55b15a-74be-11e5-9141-edd92164e7c7.png">

**Comment by balinterdi** [comment]
Thank you for spotting this, I've fixed this!
