### ISSUE TITLE
Follow through the SortableMixin => Ember.computed.sort change

### ISSUE THREAD

**Issue by balinterdi** [balinterdi/rarwe-issues#96]
Two things need to be adjusted in the subsequent chapters. The model hook needs to return `bands.get('sortedContent')` (as opposed to just `bands`) and the new band needs to be pushed to `bands.get('content')` (again, as opposed to just `bands`).

**Comment by dbouwman** [comment]
Returning `bands,get('sortedContent')` does not work - it seems to be returning the underlying array, which seems to decouple it from Bands object. Thus, when you push more things into `bands.get('content')`, the model that was passed to the controller (aka  `bands,get('sortedContent')` ) is not updated and we don't see the UI update.

Returning `bands` and then using `model.sortedContents` in the `{{#each...}}` does work though.

Code (for others having a problem)

`/app/routes/bands.js`
```
var BandsCollection = Ember.Object.extend({
  content:[],
  sortProperties:['name:desc'],
  sortedContent: Ember.computed.sort('content','sortProperties')
});

var bands = BandsCollection.create();
bands.get('content').pushObjects([the,bands,you,created,above]);

export default Ember.Route.extend({
  model: function(){
    return bands;
  },
  actions:{
    createBand: function(){
      var name = this.get('controller').get('name');
      var band = Band.create({name:name});
      bands.get('content').pushObject(band);
      this.get('controller').set('name', '');
    }
  }
});
```

`/app/templates/bands.hbs`
```
<div class="col-md-4">
  <div class="list-group">
    <div class="list-group-item">
      {{input type="text" class="new-band" placeholder="New Band" value=name}}
      <button class="btn btn-primary btn-sm new-band-button" {{action "createBand"}}>Add</button>
    </div>
    {{#each model.sortedContents as |band|}}
      {{#link-to "bands.band.songs" band class="list-group-item band-link"}}
        {{band.name}}
      {{/link-to}}
    {{/each}}
  </div>
</div>
<div class="col-md-8">
  <div class="list-group">
    {{outlet}}
  </div>
</div>

```

**Comment by balinterdi** [comment]
Thank you, Dave, that is indeed an oversight, and your solution is also the one I came up with. I'll release an update soon with some fixes (including this one). For completeness sake, the `bands.band` route also needs to change from the previous chapter and will become:

```js
```js
// app/routes/bands/band.js

export default Ember.Route.extend({
  model: function(params) {
    var bands = this.modelFor('bands');
    return bands.get('content').findBy('slug', params.slug);
  }
});
```
