### ISSUE TITLE
Double quote in Mixin example (page ~70 in ibook) "nice... you,`

### ISSUE THREAD

**Issue by sheriffderek** [balinterdi/rarwe-issues#97]
var Person = Ember.Object.extend(CanSpeak, {
  name: 'Noname',
  fillingWord: 'uhm',

  intro: function() {
    return this.speak([`Hey, I am ${this.name}.`, "nice to meet you.`]);
  }
});

**Comment by balinterdi** [comment]
Thank you for spotting this. This is already fixed in #89
